from typing import Dict, NamedTuple, Optional

from BaseClasses import Location

class T6Location(Location):
	game: str = "Touhou 6"

class T6LocationData(NamedTuple):
	category: str
	code: Optional[int] = None

def get_locations_by_category(category: str) -> Dict[str, T6LocationData]:
	location_dict: Dict[str, T6LocationData] = {}
	for name, data in location_table.items():
		if data.category == category:
			location_dict.setdefault(name, data)

	return location_dict

location_table: Dict[str, T6LocationData] = {
	## No difficulty
	# Reimu
	"[Reimu] Rumia - MidBoss":                  T6LocationData("Reimu",   91_000),
	"[Reimu] Rumia Defeated":                   T6LocationData("Reimu",   91_001),
	"[Reimu] Stage 1 Clear":                    T6LocationData("Reimu",   91_034),
	"[Reimu] Daiyousei Defeated":               T6LocationData("Reimu",   91_002),
	"[Reimu] Cirno Defeated":                   T6LocationData("Reimu",   91_004),
	"[Reimu] Stage 2 Clear":                    T6LocationData("Reimu",   91_003),
	"[Reimu] Meiling - MidBoss":                T6LocationData("Reimu",   91_006),
	"[Reimu] Meiling Defeated":                 T6LocationData("Reimu",   91_007),
	"[Reimu] Stage 3 Clear":                    T6LocationData("Reimu",   91_005),
	"[Reimu] Koakuma Defeated":                 T6LocationData("Reimu",   91_008),
	"[Reimu] Patchouli Defeated":               T6LocationData("Reimu",   91_010),
	"[Reimu] Stage 4 Clear":                    T6LocationData("Reimu",   91_009),
	"[Reimu] Sakuya - MidBoss 1":               T6LocationData("Reimu",   91_012),
	"[Reimu] Sakuya Defeated":                  T6LocationData("Reimu",   91_013),
	"[Reimu] Stage 5 Clear":                    T6LocationData("Reimu",   91_011),
	"[Reimu] Sakuya - MidBoss 2":               T6LocationData("Reimu",   91_015),
	"[Reimu] Remilia Defeated":                 T6LocationData("Reimu",   91_016),
	"[Reimu] Stage 6 Clear":                    T6LocationData("Reimu",   91_014),
	"[Reimu] Patchouli - MidBoss":              T6LocationData("Reimu",   91_036),
	"[Reimu] Flandre Defeated":                 T6LocationData("Reimu",   91_037),
	"[Reimu] Stage Extra Clear":                T6LocationData("Reimu",   91_038),

	# Marisa
	"[Marisa] Rumia - MidBoss":                 T6LocationData("Marisa",   91_017),
	"[Marisa] Rumia Defeated":                  T6LocationData("Marisa",   91_018),
	"[Marisa] Stage 1 Clear":                   T6LocationData("Marisa",   91_035),
	"[Marisa] Daiyousei Defeated":              T6LocationData("Marisa",   91_019),
	"[Marisa] Cirno Defeated":                  T6LocationData("Marisa",   91_021),
	"[Marisa] Stage 2 Clear":                   T6LocationData("Marisa",   91_020),
	"[Marisa] Meiling - MidBoss":               T6LocationData("Marisa",   91_023),
	"[Marisa] Meiling Defeated":                T6LocationData("Marisa",   91_024),
	"[Marisa] Stage 3 Clear":                   T6LocationData("Marisa",   91_022),
	"[Marisa] Koakuma Defeated":                T6LocationData("Marisa",   91_025),
	"[Marisa] Patchouli Defeated":              T6LocationData("Marisa",   91_027),
	"[Marisa] Stage 4 Clear":                   T6LocationData("Marisa",   91_026),
	"[Marisa] Sakuya - MidBoss 1":              T6LocationData("Marisa",   91_029),
	"[Marisa] Sakuya Defeated":                 T6LocationData("Marisa",   91_030),
	"[Marisa] Stage 5 Clear":                   T6LocationData("Marisa",   91_028),
	"[Marisa] Sakuya - MidBoss 2":              T6LocationData("Marisa",   91_032),
	"[Marisa] Remilia Defeated":                T6LocationData("Marisa",   91_033),
	"[Marisa] Stage 6 Clear":                   T6LocationData("Marisa",   91_031),
	"[Marisa] Patchouli - MidBoss":             T6LocationData("Marisa",   91_039),
	"[Marisa] Flandre Defeated":                T6LocationData("Marisa",   91_040),
	"[Marisa] Stage Extra Clear":               T6LocationData("Marisa",   91_041),

	# Reimu - A
	"[Reimu A] Rumia - MidBoss":                  T6LocationData("Reimu - A",   91_042),
	"[Reimu A] Rumia Defeated":                   T6LocationData("Reimu - A",   91_043),
	"[Reimu A] Stage 1 Clear":                    T6LocationData("Reimu - A",   91_044),
	"[Reimu A] Daiyousei Defeated":               T6LocationData("Reimu - A",   91_045),
	"[Reimu A] Cirno Defeated":                   T6LocationData("Reimu - A",   91_046),
	"[Reimu A] Stage 2 Clear":                    T6LocationData("Reimu - A",   91_047),
	"[Reimu A] Meiling - MidBoss":                T6LocationData("Reimu - A",   91_048),
	"[Reimu A] Meiling Defeated":                 T6LocationData("Reimu - A",   91_049),
	"[Reimu A] Stage 3 Clear":                    T6LocationData("Reimu - A",   91_050),
	"[Reimu A] Koakuma Defeated":                 T6LocationData("Reimu - A",   91_051),
	"[Reimu A] Patchouli Defeated":               T6LocationData("Reimu - A",   91_052),
	"[Reimu A] Stage 4 Clear":                    T6LocationData("Reimu - A",   91_053),
	"[Reimu A] Sakuya - MidBoss 1":               T6LocationData("Reimu - A",   91_054),
	"[Reimu A] Sakuya Defeated":                  T6LocationData("Reimu - A",   91_055),
	"[Reimu A] Stage 5 Clear":                    T6LocationData("Reimu - A",   91_056),
	"[Reimu A] Sakuya - MidBoss 2":               T6LocationData("Reimu - A",   91_057),
	"[Reimu A] Remilia Defeated":                 T6LocationData("Reimu - A",   91_058),
	"[Reimu A] Stage 6 Clear":                    T6LocationData("Reimu - A",   91_059),
	"[Reimu A] Patchouli - MidBoss":              T6LocationData("Reimu - A",   91_060),
	"[Reimu A] Flandre Defeated":                 T6LocationData("Reimu - A",   91_061),
	"[Reimu A] Stage Extra Clear":                T6LocationData("Reimu - A",   91_062),

	# Reimu - B
	"[Reimu B] Rumia - MidBoss":                  T6LocationData("Reimu - B",   91_063),
	"[Reimu B] Rumia Defeated":                   T6LocationData("Reimu - B",   91_064),
	"[Reimu B] Stage 1 Clear":                    T6LocationData("Reimu - B",   91_065),
	"[Reimu B] Daiyousei Defeated":               T6LocationData("Reimu - B",   91_066),
	"[Reimu B] Cirno Defeated":                   T6LocationData("Reimu - B",   91_067),
	"[Reimu B] Stage 2 Clear":                    T6LocationData("Reimu - B",   91_068),
	"[Reimu B] Meiling - MidBoss":                T6LocationData("Reimu - B",   91_069),
	"[Reimu B] Meiling Defeated":                 T6LocationData("Reimu - B",   91_070),
	"[Reimu B] Stage 3 Clear":                    T6LocationData("Reimu - B",   91_071),
	"[Reimu B] Koakuma Defeated":                 T6LocationData("Reimu - B",   91_072),
	"[Reimu B] Patchouli Defeated":               T6LocationData("Reimu - B",   91_073),
	"[Reimu B] Stage 4 Clear":                    T6LocationData("Reimu - B",   91_074),
	"[Reimu B] Sakuya - MidBoss 1":               T6LocationData("Reimu - B",   91_075),
	"[Reimu B] Sakuya Defeated":                  T6LocationData("Reimu - B",   91_076),
	"[Reimu B] Stage 5 Clear":                    T6LocationData("Reimu - B",   91_077),
	"[Reimu B] Sakuya - MidBoss 2":               T6LocationData("Reimu - B",   91_078),
	"[Reimu B] Remilia Defeated":                 T6LocationData("Reimu - B",   91_079),
	"[Reimu B] Stage 6 Clear":                    T6LocationData("Reimu - B",   91_080),
	"[Reimu B] Patchouli - MidBoss":              T6LocationData("Reimu - B",   91_081),
	"[Reimu B] Flandre Defeated":                 T6LocationData("Reimu - B",   91_082),
	"[Reimu B] Stage Extra Clear":                T6LocationData("Reimu - B",   91_083),

	# Marisa - A
	"[Marisa A] Rumia - MidBoss":                  T6LocationData("Marisa - A",   91_084),
	"[Marisa A] Rumia Defeated":                   T6LocationData("Marisa - A",   91_085),
	"[Marisa A] Stage 1 Clear":                    T6LocationData("Marisa - A",   91_086),
	"[Marisa A] Daiyousei Defeated":               T6LocationData("Marisa - A",   91_087),
	"[Marisa A] Cirno Defeated":                   T6LocationData("Marisa - A",   91_088),
	"[Marisa A] Stage 2 Clear":                    T6LocationData("Marisa - A",   91_089),
	"[Marisa A] Meiling - MidBoss":                T6LocationData("Marisa - A",   91_090),
	"[Marisa A] Meiling Defeated":                 T6LocationData("Marisa - A",   91_091),
	"[Marisa A] Stage 3 Clear":                    T6LocationData("Marisa - A",   91_092),
	"[Marisa A] Koakuma Defeated":                 T6LocationData("Marisa - A",   91_093),
	"[Marisa A] Patchouli Defeated":               T6LocationData("Marisa - A",   91_094),
	"[Marisa A] Stage 4 Clear":                    T6LocationData("Marisa - A",   91_095),
	"[Marisa A] Sakuya - MidBoss 1":               T6LocationData("Marisa - A",   91_096),
	"[Marisa A] Sakuya Defeated":                  T6LocationData("Marisa - A",   91_097),
	"[Marisa A] Stage 5 Clear":                    T6LocationData("Marisa - A",   91_098),
	"[Marisa A] Sakuya - MidBoss 2":               T6LocationData("Marisa - A",   91_099),
	"[Marisa A] Remilia Defeated":                 T6LocationData("Marisa - A",   91_100),
	"[Marisa A] Stage 6 Clear":                    T6LocationData("Marisa - A",   91_101),
	"[Marisa A] Patchouli - MidBoss":              T6LocationData("Marisa - A",   91_102),
	"[Marisa A] Flandre Defeated":                 T6LocationData("Marisa - A",   91_103),
	"[Marisa A] Stage Extra Clear":                T6LocationData("Marisa - A",   91_104),

	# Marisa - B
	"[Marisa B] Rumia - MidBoss":                  T6LocationData("Marisa - B",   91_105),
	"[Marisa B] Rumia Defeated":                   T6LocationData("Marisa - B",   91_106),
	"[Marisa B] Stage 1 Clear":                    T6LocationData("Marisa - B",   91_107),
	"[Marisa B] Daiyousei Defeated":               T6LocationData("Marisa - B",   91_108),
	"[Marisa B] Cirno Defeated":                   T6LocationData("Marisa - B",   91_109),
	"[Marisa B] Stage 2 Clear":                    T6LocationData("Marisa - B",   91_110),
	"[Marisa B] Meiling - MidBoss":                T6LocationData("Marisa - B",   91_111),
	"[Marisa B] Meiling Defeated":                 T6LocationData("Marisa - B",   91_112),
	"[Marisa B] Stage 3 Clear":                    T6LocationData("Marisa - B",   91_113),
	"[Marisa B] Koakuma Defeated":                 T6LocationData("Marisa - B",   91_114),
	"[Marisa B] Patchouli Defeated":               T6LocationData("Marisa - B",   91_115),
	"[Marisa B] Stage 4 Clear":                    T6LocationData("Marisa - B",   91_116),
	"[Marisa B] Sakuya - MidBoss 1":               T6LocationData("Marisa - B",   91_117),
	"[Marisa B] Sakuya Defeated":                  T6LocationData("Marisa - B",   91_118),
	"[Marisa B] Stage 5 Clear":                    T6LocationData("Marisa - B",   91_119),
	"[Marisa B] Sakuya - MidBoss 2":               T6LocationData("Marisa - B",   91_120),
	"[Marisa B] Remilia Defeated":                 T6LocationData("Marisa - B",   91_121),
	"[Marisa B] Stage 6 Clear":                    T6LocationData("Marisa - B",   91_122),
	"[Marisa B] Patchouli - MidBoss":              T6LocationData("Marisa - B",   91_123),
	"[Marisa B] Flandre Defeated":                 T6LocationData("Marisa - B",   91_124),
	"[Marisa B] Stage Extra Clear":                T6LocationData("Marisa - B",   91_125),

	## Easy
	# Reimu
	"[Easy][Reimu] Rumia - MidBoss":                  T6LocationData("Easy - Reimu",   91_126),
	"[Easy][Reimu] Rumia Defeated":                   T6LocationData("Easy - Reimu",   91_127),
	# "[Easy][Reimu] Stage 1 Clear":                    T6LocationData("Easy - Reimu",   91_128),
	"[Easy][Reimu] Daiyousei Defeated":               T6LocationData("Easy - Reimu",   91_129),
	"[Easy][Reimu] Cirno Defeated":                   T6LocationData("Easy - Reimu",   91_130),
	# "[Easy][Reimu] Stage 2 Clear":                    T6LocationData("Easy - Reimu",   91_131),
	"[Easy][Reimu] Meiling - MidBoss":                T6LocationData("Easy - Reimu",   91_132),
	"[Easy][Reimu] Meiling Defeated":                 T6LocationData("Easy - Reimu",   91_133),
	# "[Easy][Reimu] Stage 3 Clear":                    T6LocationData("Easy - Reimu",   91_134),
	"[Easy][Reimu] Koakuma Defeated":                 T6LocationData("Easy - Reimu",   91_135),
	"[Easy][Reimu] Patchouli Defeated":               T6LocationData("Easy - Reimu",   91_136),
	# "[Easy][Reimu] Stage 4 Clear":                    T6LocationData("Easy - Reimu",   91_137),
	"[Easy][Reimu] Sakuya - MidBoss 1":               T6LocationData("Easy - Reimu",   91_138),
	"[Easy][Reimu] Sakuya Defeated":                  T6LocationData("Easy - Reimu",   91_139),
	# "[Easy][Reimu] Stage 5 Clear":                    T6LocationData("Easy - Reimu",   91_140),
	# "[Easy][Reimu] Sakuya - MidBoss 2":               T6LocationData("Easy - Reimu",   91_141),
	# "[Easy][Reimu] Remilia Defeated":                 T6LocationData("Easy - Reimu",   91_142),
	# "[Easy][Reimu] Stage 6 Clear":                    T6LocationData("Easy - Reimu",   91_143),

	# Marisa
	"[Easy][Marisa] Rumia - MidBoss":                 T6LocationData("Easy - Marisa",   91_144),
	"[Easy][Marisa] Rumia Defeated":                  T6LocationData("Easy - Marisa",   91_145),
	# "[Easy][Marisa] Stage 1 Clear":                   T6LocationData("Easy - Marisa",   91_146),
	"[Easy][Marisa] Daiyousei Defeated":              T6LocationData("Easy - Marisa",   91_147),
	"[Easy][Marisa] Cirno Defeated":                  T6LocationData("Easy - Marisa",   91_148),
	# "[Easy][Marisa] Stage 2 Clear":                   T6LocationData("Easy - Marisa",   91_149),
	"[Easy][Marisa] Meiling - MidBoss":               T6LocationData("Easy - Marisa",   91_150),
	"[Easy][Marisa] Meiling Defeated":                T6LocationData("Easy - Marisa",   91_151),
	# "[Easy][Marisa] Stage 3 Clear":                   T6LocationData("Easy - Marisa",   91_152),
	"[Easy][Marisa] Koakuma Defeated":                T6LocationData("Easy - Marisa",   91_153),
	"[Easy][Marisa] Patchouli Defeated":              T6LocationData("Easy - Marisa",   91_154),
	# "[Easy][Marisa] Stage 4 Clear":                   T6LocationData("Easy - Marisa",   91_155),
	"[Easy][Marisa] Sakuya - MidBoss 1":              T6LocationData("Easy - Marisa",   91_156),
	"[Easy][Marisa] Sakuya Defeated":                 T6LocationData("Easy - Marisa",   91_157),
	# "[Easy][Marisa] Stage 5 Clear":                   T6LocationData("Easy - Marisa",   91_158),
	# "[Easy][Marisa] Sakuya - MidBoss 2":              T6LocationData("Easy - Marisa",   91_159),
	# "[Easy][Marisa] Remilia Defeated":                T6LocationData("Easy - Marisa",   91_160),
	# "[Easy][Marisa] Stage 6 Clear":                   T6LocationData("Easy - Marisa",   91_161),

	# Reimu - A
	"[Easy][Reimu A] Rumia - MidBoss":                  T6LocationData("Easy - Reimu - A",   91_162),
	"[Easy][Reimu A] Rumia Defeated":                   T6LocationData("Easy - Reimu - A",   91_163),
	# "[Easy][Reimu A] Stage 1 Clear":                    T6LocationData("Easy - Reimu - A",   91_164),
	"[Easy][Reimu A] Daiyousei Defeated":               T6LocationData("Easy - Reimu - A",   91_165),
	"[Easy][Reimu A] Cirno Defeated":                   T6LocationData("Easy - Reimu - A",   91_166),
	# "[Easy][Reimu A] Stage 2 Clear":                    T6LocationData("Easy - Reimu - A",   91_167),
	"[Easy][Reimu A] Meiling - MidBoss":                T6LocationData("Easy - Reimu - A",   91_168),
	"[Easy][Reimu A] Meiling Defeated":                 T6LocationData("Easy - Reimu - A",   91_169),
	# "[Easy][Reimu A] Stage 3 Clear":                    T6LocationData("Easy - Reimu - A",   91_170),
	"[Easy][Reimu A] Koakuma Defeated":                 T6LocationData("Easy - Reimu - A",   91_171),
	"[Easy][Reimu A] Patchouli Defeated":               T6LocationData("Easy - Reimu - A",   91_172),
	# "[Easy][Reimu A] Stage 4 Clear":                    T6LocationData("Easy - Reimu - A",   91_173),
	"[Easy][Reimu A] Sakuya - MidBoss 1":               T6LocationData("Easy - Reimu - A",   91_174),
	"[Easy][Reimu A] Sakuya Defeated":                  T6LocationData("Easy - Reimu - A",   91_175),
	# "[Easy][Reimu A] Stage 5 Clear":                    T6LocationData("Easy - Reimu - A",   91_176),
	# "[Easy][Reimu A] Sakuya - MidBoss 2":               T6LocationData("Easy - Reimu - A",   91_177),
	# "[Easy][Reimu A] Remilia Defeated":                 T6LocationData("Easy - Reimu - A",   91_178),
	# "[Easy][Reimu A] Stage 6 Clear":                    T6LocationData("Easy - Reimu - A",   91_179),

	# Reimu - B
	"[Easy][Reimu B] Rumia - MidBoss":                  T6LocationData("Easy - Reimu - B",   91_180),
	"[Easy][Reimu B] Rumia Defeated":                   T6LocationData("Easy - Reimu - B",   91_181),
	# "[Easy][Reimu B] Stage 1 Clear":                    T6LocationData("Easy - Reimu - B",   91_182),
	"[Easy][Reimu B] Daiyousei Defeated":               T6LocationData("Easy - Reimu - B",   91_183),
	"[Easy][Reimu B] Cirno Defeated":                   T6LocationData("Easy - Reimu - B",   91_184),
	# "[Easy][Reimu B] Stage 2 Clear":                    T6LocationData("Easy - Reimu - B",   91_185),
	"[Easy][Reimu B] Meiling - MidBoss":                T6LocationData("Easy - Reimu - B",   91_186),
	"[Easy][Reimu B] Meiling Defeated":                 T6LocationData("Easy - Reimu - B",   91_187),
	# "[Easy][Reimu B] Stage 3 Clear":                    T6LocationData("Easy - Reimu - B",   91_188),
	"[Easy][Reimu B] Koakuma Defeated":                 T6LocationData("Easy - Reimu - B",   91_189),
	"[Easy][Reimu B] Patchouli Defeated":               T6LocationData("Easy - Reimu - B",   91_190),
	# "[Easy][Reimu B] Stage 4 Clear":                    T6LocationData("Easy - Reimu - B",   91_191),
	"[Easy][Reimu B] Sakuya - MidBoss 1":               T6LocationData("Easy - Reimu - B",   91_192),
	"[Easy][Reimu B] Sakuya Defeated":                  T6LocationData("Easy - Reimu - B",   91_193),
	# "[Easy][Reimu B] Stage 5 Clear":                    T6LocationData("Easy - Reimu - B",   91_194),
	# "[Easy][Reimu B] Sakuya - MidBoss 2":               T6LocationData("Easy - Reimu - B",   91_195),
	# "[Easy][Reimu B] Remilia Defeated":                 T6LocationData("Easy - Reimu - B",   91_196),
	# "[Easy][Reimu B] Stage 6 Clear":                    T6LocationData("Easy - Reimu - B",   91_197),

	# Marisa - A
	"[Easy][Marisa A] Rumia - MidBoss":                  T6LocationData("Easy - Marisa - A",   91_198),
	"[Easy][Marisa A] Rumia Defeated":                   T6LocationData("Easy - Marisa - A",   91_199),
	# "[Easy][Marisa A] Stage 1 Clear":                    T6LocationData("Easy - Marisa - A",   91_200),
	"[Easy][Marisa A] Daiyousei Defeated":               T6LocationData("Easy - Marisa - A",   91_201),
	"[Easy][Marisa A] Cirno Defeated":                   T6LocationData("Easy - Marisa - A",   91_202),
	# "[Easy][Marisa A] Stage 2 Clear":                    T6LocationData("Easy - Marisa - A",   91_203),
	"[Easy][Marisa A] Meiling - MidBoss":                T6LocationData("Easy - Marisa - A",   91_204),
	"[Easy][Marisa A] Meiling Defeated":                 T6LocationData("Easy - Marisa - A",   91_205),
	# "[Easy][Marisa A] Stage 3 Clear":                    T6LocationData("Easy - Marisa - A",   91_206),
	"[Easy][Marisa A] Koakuma Defeated":                 T6LocationData("Easy - Marisa - A",   91_207),
	"[Easy][Marisa A] Patchouli Defeated":               T6LocationData("Easy - Marisa - A",   91_208),
	# "[Easy][Marisa A] Stage 4 Clear":                    T6LocationData("Easy - Marisa - A",   91_209),
	"[Easy][Marisa A] Sakuya - MidBoss 1":               T6LocationData("Easy - Marisa - A",   91_210),
	"[Easy][Marisa A] Sakuya Defeated":                  T6LocationData("Easy - Marisa - A",   91_211),
	# "[Easy][Marisa A] Stage 5 Clear":                    T6LocationData("Easy - Marisa - A",   91_212),
	# "[Easy][Marisa A] Sakuya - MidBoss 2":               T6LocationData("Easy - Marisa - A",   91_213),
	# "[Easy][Marisa A] Remilia Defeated":                 T6LocationData("Easy - Marisa - A",   91_214),
	# "[Easy][Marisa A] Stage 6 Clear":                    T6LocationData("Easy - Marisa - A",   91_215),

	# Marisa - B
	"[Easy][Marisa B] Rumia - MidBoss":                  T6LocationData("Easy - Marisa - B",   91_216),
	"[Easy][Marisa B] Rumia Defeated":                   T6LocationData("Easy - Marisa - B",   91_217),
	# "[Easy][Marisa B] Stage 1 Clear":                    T6LocationData("Easy - Marisa - B",   91_218),
	"[Easy][Marisa B] Daiyousei Defeated":               T6LocationData("Easy - Marisa - B",   91_219),
	"[Easy][Marisa B] Cirno Defeated":                   T6LocationData("Easy - Marisa - B",   91_220),
	# "[Easy][Marisa B] Stage 2 Clear":                    T6LocationData("Easy - Marisa - B",   91_221),
	"[Easy][Marisa B] Meiling - MidBoss":                T6LocationData("Easy - Marisa - B",   91_222),
	"[Easy][Marisa B] Meiling Defeated":                 T6LocationData("Easy - Marisa - B",   91_223),
	# "[Easy][Marisa B] Stage 3 Clear":                    T6LocationData("Easy - Marisa - B",   91_224),
	"[Easy][Marisa B] Koakuma Defeated":                 T6LocationData("Easy - Marisa - B",   91_225),
	"[Easy][Marisa B] Patchouli Defeated":               T6LocationData("Easy - Marisa - B",   91_226),
	# "[Easy][Marisa B] Stage 4 Clear":                    T6LocationData("Easy - Marisa - B",   91_227),
	"[Easy][Marisa B] Sakuya - MidBoss 1":               T6LocationData("Easy - Marisa - B",   91_228),
	"[Easy][Marisa B] Sakuya Defeated":                  T6LocationData("Easy - Marisa - B",   91_229),
	# "[Easy][Marisa B] Stage 5 Clear":                    T6LocationData("Easy - Marisa - B",   91_230),
	# "[Easy][Marisa B] Sakuya - MidBoss 2":               T6LocationData("Easy - Marisa - B",   91_231),
	# "[Easy][Marisa B] Remilia Defeated":                 T6LocationData("Easy - Marisa - B",   91_232),
	# "[Easy][Marisa B] Stage 6 Clear":                    T6LocationData("Easy - Marisa - B",   91_233),

	## Normal
	# Reimu
	"[Normal][Reimu] Rumia - MidBoss":                  T6LocationData("Normal - Reimu",   91_234),
	"[Normal][Reimu] Rumia Defeated":                   T6LocationData("Normal - Reimu",   91_235),
	# "[Normal][Reimu] Stage 1 Clear":                    T6LocationData("Normal - Reimu",   91_236),
	"[Normal][Reimu] Daiyousei Defeated":               T6LocationData("Normal - Reimu",   91_237),
	"[Normal][Reimu] Cirno Defeated":                   T6LocationData("Normal - Reimu",   91_238),
	# "[Normal][Reimu] Stage 2 Clear":                    T6LocationData("Normal - Reimu",   91_239),
	"[Normal][Reimu] Meiling - MidBoss":                T6LocationData("Normal - Reimu",   91_240),
	"[Normal][Reimu] Meiling Defeated":                 T6LocationData("Normal - Reimu",   91_241),
	# "[Normal][Reimu] Stage 3 Clear":                    T6LocationData("Normal - Reimu",   91_242),
	"[Normal][Reimu] Koakuma Defeated":                 T6LocationData("Normal - Reimu",   91_243),
	"[Normal][Reimu] Patchouli Defeated":               T6LocationData("Normal - Reimu",   91_244),
	# "[Normal][Reimu] Stage 4 Clear":                    T6LocationData("Normal - Reimu",   91_245),
	"[Normal][Reimu] Sakuya - MidBoss 1":               T6LocationData("Normal - Reimu",   91_246),
	"[Normal][Reimu] Sakuya Defeated":                  T6LocationData("Normal - Reimu",   91_247),
	# "[Normal][Reimu] Stage 5 Clear":                    T6LocationData("Normal - Reimu",   91_248),
	"[Normal][Reimu] Sakuya - MidBoss 2":               T6LocationData("Normal - Reimu",   91_249),
	"[Normal][Reimu] Remilia Defeated":                 T6LocationData("Normal - Reimu",   91_250),
	# "[Normal][Reimu] Stage 6 Clear":                    T6LocationData("Normal - Reimu",   91_251),

	# Marisa
	"[Normal][Marisa] Rumia - MidBoss":                 T6LocationData("Normal - Marisa",   91_252),
	"[Normal][Marisa] Rumia Defeated":                  T6LocationData("Normal - Marisa",   91_253),
	# "[Normal][Marisa] Stage 1 Clear":                   T6LocationData("Normal - Marisa",   91_254),
	"[Normal][Marisa] Daiyousei Defeated":              T6LocationData("Normal - Marisa",   91_255),
	"[Normal][Marisa] Cirno Defeated":                  T6LocationData("Normal - Marisa",   91_256),
	# "[Normal][Marisa] Stage 2 Clear":                   T6LocationData("Normal - Marisa",   91_257),
	"[Normal][Marisa] Meiling - MidBoss":               T6LocationData("Normal - Marisa",   91_258),
	"[Normal][Marisa] Meiling Defeated":                T6LocationData("Normal - Marisa",   91_259),
	# "[Normal][Marisa] Stage 3 Clear":                   T6LocationData("Normal - Marisa",   91_260),
	"[Normal][Marisa] Koakuma Defeated":                T6LocationData("Normal - Marisa",   91_261),
	"[Normal][Marisa] Patchouli Defeated":              T6LocationData("Normal - Marisa",   91_262),
	# "[Normal][Marisa] Stage 4 Clear":                   T6LocationData("Normal - Marisa",   91_263),
	"[Normal][Marisa] Sakuya - MidBoss 1":              T6LocationData("Normal - Marisa",   91_264),
	"[Normal][Marisa] Sakuya Defeated":                 T6LocationData("Normal - Marisa",   91_265),
	# "[Normal][Marisa] Stage 5 Clear":                   T6LocationData("Normal - Marisa",   91_266),
	"[Normal][Marisa] Sakuya - MidBoss 2":              T6LocationData("Normal - Marisa",   91_267),
	"[Normal][Marisa] Remilia Defeated":                T6LocationData("Normal - Marisa",   91_268),
	# "[Normal][Marisa] Stage 6 Clear":                   T6LocationData("Normal - Marisa",   91_269),

	# Reimu - A
	"[Normal][Reimu A] Rumia - MidBoss":                  T6LocationData("Normal - Reimu - A",   91_270),
	"[Normal][Reimu A] Rumia Defeated":                   T6LocationData("Normal - Reimu - A",   91_271),
	# "[Normal][Reimu A] Stage 1 Clear":                    T6LocationData("Normal - Reimu - A",   91_272),
	"[Normal][Reimu A] Daiyousei Defeated":               T6LocationData("Normal - Reimu - A",   91_273),
	"[Normal][Reimu A] Cirno Defeated":                   T6LocationData("Normal - Reimu - A",   91_274),
	# "[Normal][Reimu A] Stage 2 Clear":                    T6LocationData("Normal - Reimu - A",   91_275),
	"[Normal][Reimu A] Meiling - MidBoss":                T6LocationData("Normal - Reimu - A",   91_276),
	"[Normal][Reimu A] Meiling Defeated":                 T6LocationData("Normal - Reimu - A",   91_277),
	# "[Normal][Reimu A] Stage 3 Clear":                    T6LocationData("Normal - Reimu - A",   91_278),
	"[Normal][Reimu A] Koakuma Defeated":                 T6LocationData("Normal - Reimu - A",   91_279),
	"[Normal][Reimu A] Patchouli Defeated":               T6LocationData("Normal - Reimu - A",   91_280),
	# "[Normal][Reimu A] Stage 4 Clear":                    T6LocationData("Normal - Reimu - A",   91_281),
	"[Normal][Reimu A] Sakuya - MidBoss 1":               T6LocationData("Normal - Reimu - A",   91_282),
	"[Normal][Reimu A] Sakuya Defeated":                  T6LocationData("Normal - Reimu - A",   91_283),
	# "[Normal][Reimu A] Stage 5 Clear":                    T6LocationData("Normal - Reimu - A",   91_284),
	"[Normal][Reimu A] Sakuya - MidBoss 2":               T6LocationData("Normal - Reimu - A",   91_285),
	"[Normal][Reimu A] Remilia Defeated":                 T6LocationData("Normal - Reimu - A",   91_286),
	# "[Normal][Reimu A] Stage 6 Clear":                    T6LocationData("Normal - Reimu - A",   91_287),

	# Reimu - B
	"[Normal][Reimu B] Rumia - MidBoss":                  T6LocationData("Normal - Reimu - B",   91_288),
	"[Normal][Reimu B] Rumia Defeated":                   T6LocationData("Normal - Reimu - B",   91_289),
	# "[Normal][Reimu B] Stage 1 Clear":                    T6LocationData("Normal - Reimu - B",   91_290),
	"[Normal][Reimu B] Daiyousei Defeated":               T6LocationData("Normal - Reimu - B",   91_291),
	"[Normal][Reimu B] Cirno Defeated":                   T6LocationData("Normal - Reimu - B",   91_292),
	# "[Normal][Reimu B] Stage 2 Clear":                    T6LocationData("Normal - Reimu - B",   91_293),
	"[Normal][Reimu B] Meiling - MidBoss":                T6LocationData("Normal - Reimu - B",   91_294),
	"[Normal][Reimu B] Meiling Defeated":                 T6LocationData("Normal - Reimu - B",   91_295),
	# "[Normal][Reimu B] Stage 3 Clear":                    T6LocationData("Normal - Reimu - B",   91_296),
	"[Normal][Reimu B] Koakuma Defeated":                 T6LocationData("Normal - Reimu - B",   91_297),
	"[Normal][Reimu B] Patchouli Defeated":               T6LocationData("Normal - Reimu - B",   91_298),
	# "[Normal][Reimu B] Stage 4 Clear":                    T6LocationData("Normal - Reimu - B",   91_299),
	"[Normal][Reimu B] Sakuya - MidBoss 1":               T6LocationData("Normal - Reimu - B",   91_300),
	"[Normal][Reimu B] Sakuya Defeated":                  T6LocationData("Normal - Reimu - B",   91_301),
	# "[Normal][Reimu B] Stage 5 Clear":                    T6LocationData("Normal - Reimu - B",   91_302),
	"[Normal][Reimu B] Sakuya - MidBoss 2":               T6LocationData("Normal - Reimu - B",   91_303),
	"[Normal][Reimu B] Remilia Defeated":                 T6LocationData("Normal - Reimu - B",   91_304),
	# "[Normal][Reimu B] Stage 6 Clear":                    T6LocationData("Normal - Reimu - B",   91_305),

	# Marisa - A
	"[Normal][Marisa A] Rumia - MidBoss":                  T6LocationData("Normal - Marisa - A",   91_306),
	"[Normal][Marisa A] Rumia Defeated":                   T6LocationData("Normal - Marisa - A",   91_307),
	# "[Normal][Marisa A] Stage 1 Clear":                    T6LocationData("Normal - Marisa - A",   91_308),
	"[Normal][Marisa A] Daiyousei Defeated":               T6LocationData("Normal - Marisa - A",   91_309),
	"[Normal][Marisa A] Cirno Defeated":                   T6LocationData("Normal - Marisa - A",   91_310),
	# "[Normal][Marisa A] Stage 2 Clear":                    T6LocationData("Normal - Marisa - A",   91_311),
	"[Normal][Marisa A] Meiling - MidBoss":                T6LocationData("Normal - Marisa - A",   91_312),
	"[Normal][Marisa A] Meiling Defeated":                 T6LocationData("Normal - Marisa - A",   91_313),
	# "[Normal][Marisa A] Stage 3 Clear":                    T6LocationData("Normal - Marisa - A",   91_314),
	"[Normal][Marisa A] Koakuma Defeated":                 T6LocationData("Normal - Marisa - A",   91_315),
	"[Normal][Marisa A] Patchouli Defeated":               T6LocationData("Normal - Marisa - A",   91_316),
	# "[Normal][Marisa A] Stage 4 Clear":                    T6LocationData("Normal - Marisa - A",   91_317),
	"[Normal][Marisa A] Sakuya - MidBoss 1":               T6LocationData("Normal - Marisa - A",   91_318),
	"[Normal][Marisa A] Sakuya Defeated":                  T6LocationData("Normal - Marisa - A",   91_319),
	# "[Normal][Marisa A] Stage 5 Clear":                    T6LocationData("Normal - Marisa - A",   91_320),
	"[Normal][Marisa A] Sakuya - MidBoss 2":               T6LocationData("Normal - Marisa - A",   91_321),
	"[Normal][Marisa A] Remilia Defeated":                 T6LocationData("Normal - Marisa - A",   91_322),
	# "[Normal][Marisa A] Stage 6 Clear":                    T6LocationData("Normal - Marisa - A",   91_323),

	# Marisa - B
	"[Normal][Marisa B] Rumia - MidBoss":                  T6LocationData("Normal - Marisa - B",   91_324),
	"[Normal][Marisa B] Rumia Defeated":                   T6LocationData("Normal - Marisa - B",   91_325),
	# "[Normal][Marisa B] Stage 1 Clear":                    T6LocationData("Normal - Marisa - B",   91_326),
	"[Normal][Marisa B] Daiyousei Defeated":               T6LocationData("Normal - Marisa - B",   91_327),
	"[Normal][Marisa B] Cirno Defeated":                   T6LocationData("Normal - Marisa - B",   91_328),
	# "[Normal][Marisa B] Stage 2 Clear":                    T6LocationData("Normal - Marisa - B",   91_329),
	"[Normal][Marisa B] Meiling - MidBoss":                T6LocationData("Normal - Marisa - B",   91_330),
	"[Normal][Marisa B] Meiling Defeated":                 T6LocationData("Normal - Marisa - B",   91_331),
	# "[Normal][Marisa B] Stage 3 Clear":                    T6LocationData("Normal - Marisa - B",   91_332),
	"[Normal][Marisa B] Koakuma Defeated":                 T6LocationData("Normal - Marisa - B",   91_333),
	"[Normal][Marisa B] Patchouli Defeated":               T6LocationData("Normal - Marisa - B",   91_334),
	# "[Normal][Marisa B] Stage 4 Clear":                    T6LocationData("Normal - Marisa - B",   91_335),
	"[Normal][Marisa B] Sakuya - MidBoss 1":               T6LocationData("Normal - Marisa - B",   91_336),
	"[Normal][Marisa B] Sakuya Defeated":                  T6LocationData("Normal - Marisa - B",   91_337),
	# "[Normal][Marisa B] Stage 5 Clear":                    T6LocationData("Normal - Marisa - B",   91_338),
	"[Normal][Marisa B] Sakuya - MidBoss 2":               T6LocationData("Normal - Marisa - B",   91_339),
	"[Normal][Marisa B] Remilia Defeated":                 T6LocationData("Normal - Marisa - B",   91_340),
	# "[Normal][Marisa B] Stage 6 Clear":                    T6LocationData("Normal - Marisa - B",   91_341),

	## Hard
	# Reimu
	"[Hard][Reimu] Rumia - MidBoss":                  T6LocationData("Hard - Reimu",   91_342),
	"[Hard][Reimu] Rumia Defeated":                   T6LocationData("Hard - Reimu",   91_343),
	# "[Hard][Reimu] Stage 1 Clear":                    T6LocationData("Hard - Reimu",   91_344),
	"[Hard][Reimu] Daiyousei Defeated":               T6LocationData("Hard - Reimu",   91_345),
	"[Hard][Reimu] Cirno Defeated":                   T6LocationData("Hard - Reimu",   91_346),
	# "[Hard][Reimu] Stage 2 Clear":                    T6LocationData("Hard - Reimu",   91_347),
	"[Hard][Reimu] Meiling - MidBoss":                T6LocationData("Hard - Reimu",   91_348),
	"[Hard][Reimu] Meiling Defeated":                 T6LocationData("Hard - Reimu",   91_349),
	# "[Hard][Reimu] Stage 3 Clear":                    T6LocationData("Hard - Reimu",   91_350),
	"[Hard][Reimu] Koakuma Defeated":                 T6LocationData("Hard - Reimu",   91_351),
	"[Hard][Reimu] Patchouli Defeated":               T6LocationData("Hard - Reimu",   91_352),
	# "[Hard][Reimu] Stage 4 Clear":                    T6LocationData("Hard - Reimu",   91_353),
	"[Hard][Reimu] Sakuya - MidBoss 1":               T6LocationData("Hard - Reimu",   91_354),
	"[Hard][Reimu] Sakuya Defeated":                  T6LocationData("Hard - Reimu",   91_355),
	# "[Hard][Reimu] Stage 5 Clear":                    T6LocationData("Hard - Reimu",   91_356),
	"[Hard][Reimu] Sakuya - MidBoss 2":               T6LocationData("Hard - Reimu",   91_357),
	"[Hard][Reimu] Remilia Defeated":                 T6LocationData("Hard - Reimu",   91_358),
	# "[Hard][Reimu] Stage 6 Clear":                    T6LocationData("Hard - Reimu",   91_359),

	# Marisa
	"[Hard][Marisa] Rumia - MidBoss":                 T6LocationData("Hard - Marisa",   91_360),
	"[Hard][Marisa] Rumia Defeated":                  T6LocationData("Hard - Marisa",   91_361),
	# "[Hard][Marisa] Stage 1 Clear":                   T6LocationData("Hard - Marisa",   91_362),
	"[Hard][Marisa] Daiyousei Defeated":              T6LocationData("Hard - Marisa",   91_363),
	"[Hard][Marisa] Cirno Defeated":                  T6LocationData("Hard - Marisa",   91_364),
	# "[Hard][Marisa] Stage 2 Clear":                   T6LocationData("Hard - Marisa",   91_365),
	"[Hard][Marisa] Meiling - MidBoss":               T6LocationData("Hard - Marisa",   91_366),
	"[Hard][Marisa] Meiling Defeated":                T6LocationData("Hard - Marisa",   91_367),
	# "[Hard][Marisa] Stage 3 Clear":                   T6LocationData("Hard - Marisa",   91_368),
	"[Hard][Marisa] Koakuma Defeated":                T6LocationData("Hard - Marisa",   91_369),
	"[Hard][Marisa] Patchouli Defeated":              T6LocationData("Hard - Marisa",   91_370),
	# "[Hard][Marisa] Stage 4 Clear":                   T6LocationData("Hard - Marisa",   91_371),
	"[Hard][Marisa] Sakuya - MidBoss 1":              T6LocationData("Hard - Marisa",   91_372),
	"[Hard][Marisa] Sakuya Defeated":                 T6LocationData("Hard - Marisa",   91_373),
	# "[Hard][Marisa] Stage 5 Clear":                   T6LocationData("Hard - Marisa",   91_374),
	"[Hard][Marisa] Sakuya - MidBoss 2":              T6LocationData("Hard - Marisa",   91_375),
	"[Hard][Marisa] Remilia Defeated":                T6LocationData("Hard - Marisa",   91_376),
	# "[Hard][Marisa] Stage 6 Clear":                   T6LocationData("Hard - Marisa",   91_377),

	# Reimu - A
	"[Hard][Reimu A] Rumia - MidBoss":                  T6LocationData("Hard - Reimu - A",   91_378),
	"[Hard][Reimu A] Rumia Defeated":                   T6LocationData("Hard - Reimu - A",   91_379),
	# "[Hard][Reimu A] Stage 1 Clear":                    T6LocationData("Hard - Reimu - A",   91_380),
	"[Hard][Reimu A] Daiyousei Defeated":               T6LocationData("Hard - Reimu - A",   91_381),
	"[Hard][Reimu A] Cirno Defeated":                   T6LocationData("Hard - Reimu - A",   91_382),
	# "[Hard][Reimu A] Stage 2 Clear":                    T6LocationData("Hard - Reimu - A",   91_383),
	"[Hard][Reimu A] Meiling - MidBoss":                T6LocationData("Hard - Reimu - A",   91_384),
	"[Hard][Reimu A] Meiling Defeated":                 T6LocationData("Hard - Reimu - A",   91_385),
	# "[Hard][Reimu A] Stage 3 Clear":                    T6LocationData("Hard - Reimu - A",   91_386),
	"[Hard][Reimu A] Koakuma Defeated":                 T6LocationData("Hard - Reimu - A",   91_387),
	"[Hard][Reimu A] Patchouli Defeated":               T6LocationData("Hard - Reimu - A",   91_388),
	# "[Hard][Reimu A] Stage 4 Clear":                    T6LocationData("Hard - Reimu - A",   91_389),
	"[Hard][Reimu A] Sakuya - MidBoss 1":               T6LocationData("Hard - Reimu - A",   91_390),
	"[Hard][Reimu A] Sakuya Defeated":                  T6LocationData("Hard - Reimu - A",   91_391),
	# "[Hard][Reimu A] Stage 5 Clear":                    T6LocationData("Hard - Reimu - A",   91_392),
	"[Hard][Reimu A] Sakuya - MidBoss 2":               T6LocationData("Hard - Reimu - A",   91_393),
	"[Hard][Reimu A] Remilia Defeated":                 T6LocationData("Hard - Reimu - A",   91_394),
	# "[Hard][Reimu A] Stage 6 Clear":                    T6LocationData("Hard - Reimu - A",   91_395),

	# Reimu - B
	"[Hard][Reimu B] Rumia - MidBoss":                  T6LocationData("Hard - Reimu - B",   91_396),
	"[Hard][Reimu B] Rumia Defeated":                   T6LocationData("Hard - Reimu - B",   91_397),
	# "[Hard][Reimu B] Stage 1 Clear":                    T6LocationData("Hard - Reimu - B",   91_398),
	"[Hard][Reimu B] Daiyousei Defeated":               T6LocationData("Hard - Reimu - B",   91_399),
	"[Hard][Reimu B] Cirno Defeated":                   T6LocationData("Hard - Reimu - B",   91_400),
	# "[Hard][Reimu B] Stage 2 Clear":                    T6LocationData("Hard - Reimu - B",   91_401),
	"[Hard][Reimu B] Meiling - MidBoss":                T6LocationData("Hard - Reimu - B",   91_402),
	"[Hard][Reimu B] Meiling Defeated":                 T6LocationData("Hard - Reimu - B",   91_403),
	# "[Hard][Reimu B] Stage 3 Clear":                    T6LocationData("Hard - Reimu - B",   91_404),
	"[Hard][Reimu B] Koakuma Defeated":                 T6LocationData("Hard - Reimu - B",   91_405),
	"[Hard][Reimu B] Patchouli Defeated":               T6LocationData("Hard - Reimu - B",   91_406),
	# "[Hard][Reimu B] Stage 4 Clear":                    T6LocationData("Hard - Reimu - B",   91_407),
	"[Hard][Reimu B] Sakuya - MidBoss 1":               T6LocationData("Hard - Reimu - B",   91_408),
	"[Hard][Reimu B] Sakuya Defeated":                  T6LocationData("Hard - Reimu - B",   91_409),
	# "[Hard][Reimu B] Stage 5 Clear":                    T6LocationData("Hard - Reimu - B",   91_410),
	"[Hard][Reimu B] Sakuya - MidBoss 2":               T6LocationData("Hard - Reimu - B",   91_411),
	"[Hard][Reimu B] Remilia Defeated":                 T6LocationData("Hard - Reimu - B",   91_412),
	# "[Hard][Reimu B] Stage 6 Clear":                    T6LocationData("Hard - Reimu - B",   91_413),

	# Marisa - A
	"[Hard][Marisa A] Rumia - MidBoss":                  T6LocationData("Hard - Marisa - A",   91_414),
	"[Hard][Marisa A] Rumia Defeated":                   T6LocationData("Hard - Marisa - A",   91_415),
	# "[Hard][Marisa A] Stage 1 Clear":                    T6LocationData("Hard - Marisa - A",   91_416),
	"[Hard][Marisa A] Daiyousei Defeated":               T6LocationData("Hard - Marisa - A",   91_417),
	"[Hard][Marisa A] Cirno Defeated":                   T6LocationData("Hard - Marisa - A",   91_418),
	# "[Hard][Marisa A] Stage 2 Clear":                    T6LocationData("Hard - Marisa - A",   91_419),
	"[Hard][Marisa A] Meiling - MidBoss":                T6LocationData("Hard - Marisa - A",   91_420),
	"[Hard][Marisa A] Meiling Defeated":                 T6LocationData("Hard - Marisa - A",   91_421),
	# "[Hard][Marisa A] Stage 3 Clear":                    T6LocationData("Hard - Marisa - A",   91_422),
	"[Hard][Marisa A] Koakuma Defeated":                 T6LocationData("Hard - Marisa - A",   91_423),
	"[Hard][Marisa A] Patchouli Defeated":               T6LocationData("Hard - Marisa - A",   91_424),
	# "[Hard][Marisa A] Stage 4 Clear":                    T6LocationData("Hard - Marisa - A",   91_425),
	"[Hard][Marisa A] Sakuya - MidBoss 1":               T6LocationData("Hard - Marisa - A",   91_426),
	"[Hard][Marisa A] Sakuya Defeated":                  T6LocationData("Hard - Marisa - A",   91_427),
	# "[Hard][Marisa A] Stage 5 Clear":                    T6LocationData("Hard - Marisa - A",   91_428),
	"[Hard][Marisa A] Sakuya - MidBoss 2":               T6LocationData("Hard - Marisa - A",   91_429),
	"[Hard][Marisa A] Remilia Defeated":                 T6LocationData("Hard - Marisa - A",   91_430),
	# "[Hard][Marisa A] Stage 6 Clear":                    T6LocationData("Hard - Marisa - A",   91_431),

	# Marisa - B
	"[Hard][Marisa B] Rumia - MidBoss":                  T6LocationData("Hard - Marisa - B",   91_432),
	"[Hard][Marisa B] Rumia Defeated":                   T6LocationData("Hard - Marisa - B",   91_433),
	# "[Hard][Marisa B] Stage 1 Clear":                    T6LocationData("Hard - Marisa - B",   91_434),
	"[Hard][Marisa B] Daiyousei Defeated":               T6LocationData("Hard - Marisa - B",   91_435),
	"[Hard][Marisa B] Cirno Defeated":                   T6LocationData("Hard - Marisa - B",   91_436),
	# "[Hard][Marisa B] Stage 2 Clear":                    T6LocationData("Hard - Marisa - B",   91_437),
	"[Hard][Marisa B] Meiling - MidBoss":                T6LocationData("Hard - Marisa - B",   91_438),
	"[Hard][Marisa B] Meiling Defeated":                 T6LocationData("Hard - Marisa - B",   91_439),
	# "[Hard][Marisa B] Stage 3 Clear":                    T6LocationData("Hard - Marisa - B",   91_440),
	"[Hard][Marisa B] Koakuma Defeated":                 T6LocationData("Hard - Marisa - B",   91_441),
	"[Hard][Marisa B] Patchouli Defeated":               T6LocationData("Hard - Marisa - B",   91_442),
	# "[Hard][Marisa B] Stage 4 Clear":                    T6LocationData("Hard - Marisa - B",   91_443),
	"[Hard][Marisa B] Sakuya - MidBoss 1":               T6LocationData("Hard - Marisa - B",   91_444),
	"[Hard][Marisa B] Sakuya Defeated":                  T6LocationData("Hard - Marisa - B",   91_445),
	# "[Hard][Marisa B] Stage 5 Clear":                    T6LocationData("Hard - Marisa - B",   91_446),
	"[Hard][Marisa B] Sakuya - MidBoss 2":               T6LocationData("Hard - Marisa - B",   91_447),
	"[Hard][Marisa B] Remilia Defeated":                 T6LocationData("Hard - Marisa - B",   91_448),
	# "[Hard][Marisa B] Stage 6 Clear":                    T6LocationData("Hard - Marisa - B",   91_449),

	## Lunatic
	# Reimu
	"[Lunatic][Reimu] Rumia - MidBoss":                  T6LocationData("Lunatic - Reimu",   91_450),
	"[Lunatic][Reimu] Rumia Defeated":                   T6LocationData("Lunatic - Reimu",   91_451),
	# "[Lunatic][Reimu] Stage 1 Clear":                    T6LocationData("Lunatic - Reimu",   91_452),
	"[Lunatic][Reimu] Daiyousei Defeated":               T6LocationData("Lunatic - Reimu",   91_453),
	"[Lunatic][Reimu] Cirno Defeated":                   T6LocationData("Lunatic - Reimu",   91_454),
	# "[Lunatic][Reimu] Stage 2 Clear":                    T6LocationData("Lunatic - Reimu",   91_455),
	"[Lunatic][Reimu] Meiling - MidBoss":                T6LocationData("Lunatic - Reimu",   91_456),
	"[Lunatic][Reimu] Meiling Defeated":                 T6LocationData("Lunatic - Reimu",   91_457),
	# "[Lunatic][Reimu] Stage 3 Clear":                    T6LocationData("Lunatic - Reimu",   91_458),
	"[Lunatic][Reimu] Koakuma Defeated":                 T6LocationData("Lunatic - Reimu",   91_459),
	"[Lunatic][Reimu] Patchouli Defeated":               T6LocationData("Lunatic - Reimu",   91_460),
	# "[Lunatic][Reimu] Stage 4 Clear":                    T6LocationData("Lunatic - Reimu",   91_461),
	"[Lunatic][Reimu] Sakuya - MidBoss 1":               T6LocationData("Lunatic - Reimu",   91_462),
	"[Lunatic][Reimu] Sakuya Defeated":                  T6LocationData("Lunatic - Reimu",   91_463),
	# "[Lunatic][Reimu] Stage 5 Clear":                    T6LocationData("Lunatic - Reimu",   91_464),
	"[Lunatic][Reimu] Sakuya - MidBoss 2":               T6LocationData("Lunatic - Reimu",   91_465),
	"[Lunatic][Reimu] Remilia Defeated":                 T6LocationData("Lunatic - Reimu",   91_466),
	# "[Lunatic][Reimu] Stage 6 Clear":                    T6LocationData("Lunatic - Reimu",   91_467),

	# Marisa
	"[Lunatic][Marisa] Rumia - MidBoss":                 T6LocationData("Lunatic - Marisa",   91_468),
	"[Lunatic][Marisa] Rumia Defeated":                  T6LocationData("Lunatic - Marisa",   91_469),
	# "[Lunatic][Marisa] Stage 1 Clear":                   T6LocationData("Lunatic - Marisa",   91_470),
	"[Lunatic][Marisa] Daiyousei Defeated":              T6LocationData("Lunatic - Marisa",   91_471),
	"[Lunatic][Marisa] Cirno Defeated":                  T6LocationData("Lunatic - Marisa",   91_472),
	# "[Lunatic][Marisa] Stage 2 Clear":                   T6LocationData("Lunatic - Marisa",   91_473),
	"[Lunatic][Marisa] Meiling - MidBoss":               T6LocationData("Lunatic - Marisa",   91_474),
	"[Lunatic][Marisa] Meiling Defeated":                T6LocationData("Lunatic - Marisa",   91_475),
	# "[Lunatic][Marisa] Stage 3 Clear":                   T6LocationData("Lunatic - Marisa",   91_476),
	"[Lunatic][Marisa] Koakuma Defeated":                T6LocationData("Lunatic - Marisa",   91_477),
	"[Lunatic][Marisa] Patchouli Defeated":              T6LocationData("Lunatic - Marisa",   91_478),
	# "[Lunatic][Marisa] Stage 4 Clear":                   T6LocationData("Lunatic - Marisa",   91_479),
	"[Lunatic][Marisa] Sakuya - MidBoss 1":              T6LocationData("Lunatic - Marisa",   91_480),
	"[Lunatic][Marisa] Sakuya Defeated":                 T6LocationData("Lunatic - Marisa",   91_481),
	# "[Lunatic][Marisa] Stage 5 Clear":                   T6LocationData("Lunatic - Marisa",   91_482),
	"[Lunatic][Marisa] Sakuya - MidBoss 2":              T6LocationData("Lunatic - Marisa",   91_483),
	"[Lunatic][Marisa] Remilia Defeated":                T6LocationData("Lunatic - Marisa",   91_484),
	# "[Lunatic][Marisa] Stage 6 Clear":                   T6LocationData("Lunatic - Marisa",   91_485),

	# Reimu - A
	"[Lunatic][Reimu A] Rumia - MidBoss":                  T6LocationData("Lunatic - Reimu - A",   91_486),
	"[Lunatic][Reimu A] Rumia Defeated":                   T6LocationData("Lunatic - Reimu - A",   91_487),
	# "[Lunatic][Reimu A] Stage 1 Clear":                    T6LocationData("Lunatic - Reimu - A",   91_488),
	"[Lunatic][Reimu A] Daiyousei Defeated":               T6LocationData("Lunatic - Reimu - A",   91_489),
	"[Lunatic][Reimu A] Cirno Defeated":                   T6LocationData("Lunatic - Reimu - A",   91_490),
	# "[Lunatic][Reimu A] Stage 2 Clear":                    T6LocationData("Lunatic - Reimu - A",   91_491),
	"[Lunatic][Reimu A] Meiling - MidBoss":                T6LocationData("Lunatic - Reimu - A",   91_492),
	"[Lunatic][Reimu A] Meiling Defeated":                 T6LocationData("Lunatic - Reimu - A",   91_493),
	# "[Lunatic][Reimu A] Stage 3 Clear":                    T6LocationData("Lunatic - Reimu - A",   91_494),
	"[Lunatic][Reimu A] Koakuma Defeated":                 T6LocationData("Lunatic - Reimu - A",   91_495),
	"[Lunatic][Reimu A] Patchouli Defeated":               T6LocationData("Lunatic - Reimu - A",   91_496),
	# "[Lunatic][Reimu A] Stage 4 Clear":                    T6LocationData("Lunatic - Reimu - A",   91_497),
	"[Lunatic][Reimu A] Sakuya - MidBoss 1":               T6LocationData("Lunatic - Reimu - A",   91_498),
	"[Lunatic][Reimu A] Sakuya Defeated":                  T6LocationData("Lunatic - Reimu - A",   91_499),
	# "[Lunatic][Reimu A] Stage 5 Clear":                    T6LocationData("Lunatic - Reimu - A",   91_500),
	"[Lunatic][Reimu A] Sakuya - MidBoss 2":               T6LocationData("Lunatic - Reimu - A",   91_501),
	"[Lunatic][Reimu A] Remilia Defeated":                 T6LocationData("Lunatic - Reimu - A",   91_502),
	# "[Lunatic][Reimu A] Stage 6 Clear":                    T6LocationData("Lunatic - Reimu - A",   91_503),

	# Reimu - B
	"[Lunatic][Reimu B] Rumia - MidBoss":                  T6LocationData("Lunatic - Reimu - B",   91_504),
	"[Lunatic][Reimu B] Rumia Defeated":                   T6LocationData("Lunatic - Reimu - B",   91_505),
	# "[Lunatic][Reimu B] Stage 1 Clear":                    T6LocationData("Lunatic - Reimu - B",   91_506),
	"[Lunatic][Reimu B] Daiyousei Defeated":               T6LocationData("Lunatic - Reimu - B",   91_507),
	"[Lunatic][Reimu B] Cirno Defeated":                   T6LocationData("Lunatic - Reimu - B",   91_508),
	# "[Lunatic][Reimu B] Stage 2 Clear":                    T6LocationData("Lunatic - Reimu - B",   91_509),
	"[Lunatic][Reimu B] Meiling - MidBoss":                T6LocationData("Lunatic - Reimu - B",   91_510),
	"[Lunatic][Reimu B] Meiling Defeated":                 T6LocationData("Lunatic - Reimu - B",   91_511),
	# "[Lunatic][Reimu B] Stage 3 Clear":                    T6LocationData("Lunatic - Reimu - B",   91_512),
	"[Lunatic][Reimu B] Koakuma Defeated":                 T6LocationData("Lunatic - Reimu - B",   91_513),
	"[Lunatic][Reimu B] Patchouli Defeated":               T6LocationData("Lunatic - Reimu - B",   91_514),
	# "[Lunatic][Reimu B] Stage 4 Clear":                    T6LocationData("Lunatic - Reimu - B",   91_515),
	"[Lunatic][Reimu B] Sakuya - MidBoss 1":               T6LocationData("Lunatic - Reimu - B",   91_516),
	"[Lunatic][Reimu B] Sakuya Defeated":                  T6LocationData("Lunatic - Reimu - B",   91_517),
	# "[Lunatic][Reimu B] Stage 5 Clear":                    T6LocationData("Lunatic - Reimu - B",   91_518),
	"[Lunatic][Reimu B] Sakuya - MidBoss 2":               T6LocationData("Lunatic - Reimu - B",   91_519),
	"[Lunatic][Reimu B] Remilia Defeated":                 T6LocationData("Lunatic - Reimu - B",   91_520),
	# "[Lunatic][Reimu B] Stage 6 Clear":                    T6LocationData("Lunatic - Reimu - B",   91_521),

	# Marisa - A
	"[Lunatic][Marisa A] Rumia - MidBoss":                  T6LocationData("Lunatic - Marisa - A",   91_522),
	"[Lunatic][Marisa A] Rumia Defeated":                   T6LocationData("Lunatic - Marisa - A",   91_523),
	# "[Lunatic][Marisa A] Stage 1 Clear":                    T6LocationData("Lunatic - Marisa - A",   91_524),
	"[Lunatic][Marisa A] Daiyousei Defeated":               T6LocationData("Lunatic - Marisa - A",   91_525),
	"[Lunatic][Marisa A] Cirno Defeated":                   T6LocationData("Lunatic - Marisa - A",   91_526),
	# "[Lunatic][Marisa A] Stage 2 Clear":                    T6LocationData("Lunatic - Marisa - A",   91_527),
	"[Lunatic][Marisa A] Meiling - MidBoss":                T6LocationData("Lunatic - Marisa - A",   91_528),
	"[Lunatic][Marisa A] Meiling Defeated":                 T6LocationData("Lunatic - Marisa - A",   91_529),
	# "[Lunatic][Marisa A] Stage 3 Clear":                    T6LocationData("Lunatic - Marisa - A",   91_530),
	"[Lunatic][Marisa A] Koakuma Defeated":                 T6LocationData("Lunatic - Marisa - A",   91_531),
	"[Lunatic][Marisa A] Patchouli Defeated":               T6LocationData("Lunatic - Marisa - A",   91_532),
	# "[Lunatic][Marisa A] Stage 4 Clear":                    T6LocationData("Lunatic - Marisa - A",   91_533),
	"[Lunatic][Marisa A] Sakuya - MidBoss 1":               T6LocationData("Lunatic - Marisa - A",   91_534),
	"[Lunatic][Marisa A] Sakuya Defeated":                  T6LocationData("Lunatic - Marisa - A",   91_535),
	# "[Lunatic][Marisa A] Stage 5 Clear":                    T6LocationData("Lunatic - Marisa - A",   91_536),
	"[Lunatic][Marisa A] Sakuya - MidBoss 2":               T6LocationData("Lunatic - Marisa - A",   91_537),
	"[Lunatic][Marisa A] Remilia Defeated":                 T6LocationData("Lunatic - Marisa - A",   91_538),
	# "[Lunatic][Marisa A] Stage 6 Clear":                    T6LocationData("Lunatic - Marisa - A",   91_539),

	# Marisa - B
	"[Lunatic][Marisa B] Rumia - MidBoss":                  T6LocationData("Lunatic - Marisa - B",   91_540),
	"[Lunatic][Marisa B] Rumia Defeated":                   T6LocationData("Lunatic - Marisa - B",   91_541),
	# "[Lunatic][Marisa B] Stage 1 Clear":                    T6LocationData("Lunatic - Marisa - B",   91_542),
	"[Lunatic][Marisa B] Daiyousei Defeated":               T6LocationData("Lunatic - Marisa - B",   91_543),
	"[Lunatic][Marisa B] Cirno Defeated":                   T6LocationData("Lunatic - Marisa - B",   91_544),
	# "[Lunatic][Marisa B] Stage 2 Clear":                    T6LocationData("Lunatic - Marisa - B",   91_545),
	"[Lunatic][Marisa B] Meiling - MidBoss":                T6LocationData("Lunatic - Marisa - B",   91_546),
	"[Lunatic][Marisa B] Meiling Defeated":                 T6LocationData("Lunatic - Marisa - B",   91_547),
	# "[Lunatic][Marisa B] Stage 3 Clear":                    T6LocationData("Lunatic - Marisa - B",   91_548),
	"[Lunatic][Marisa B] Koakuma Defeated":                 T6LocationData("Lunatic - Marisa - B",   91_549),
	"[Lunatic][Marisa B] Patchouli Defeated":               T6LocationData("Lunatic - Marisa - B",   91_550),
	# "[Lunatic][Marisa B] Stage 4 Clear":                    T6LocationData("Lunatic - Marisa - B",   91_551),
	"[Lunatic][Marisa B] Sakuya - MidBoss 1":               T6LocationData("Lunatic - Marisa - B",   91_552),
	"[Lunatic][Marisa B] Sakuya Defeated":                  T6LocationData("Lunatic - Marisa - B",   91_553),
	# "[Lunatic][Marisa B] Stage 5 Clear":                    T6LocationData("Lunatic - Marisa - B",   91_554),
	"[Lunatic][Marisa B] Sakuya - MidBoss 2":               T6LocationData("Lunatic - Marisa - B",   91_555),
	"[Lunatic][Marisa B] Remilia Defeated":                 T6LocationData("Lunatic - Marisa - B",   91_556),
	# "[Lunatic][Marisa B] Stage 6 Clear":                    T6LocationData("Lunatic - Marisa - B",   91_557),
}

event_location_table: Dict[str, T6LocationData] = {}