from typing import Dict, NamedTuple, Optional

from BaseClasses import Location

class TLocation(Location):
	game: str = "Touhou 6"

class TLocationData(NamedTuple):
	category: str
	code: Optional[int] = None

def get_locations_by_category(category: str) -> Dict[str, TLocationData]:
	location_dict: Dict[str, TLocationData] = {}
	for name, data in location_table.items():
		if data.category == category:
			location_dict.setdefault(name, data)

	return location_dict

location_table: Dict[str, TLocationData] = {
	## No difficulty
	# Reimu
	"[Reimu] Rumia - MidBoss":                  TLocationData("Reimu",   91000),
	"[Reimu] Rumia Defeated":                   TLocationData("Reimu",   91001),
	"[Reimu] Stage 1 Clear":                    TLocationData("Reimu",   91034),
	"[Reimu] Daiyousei Defeated":               TLocationData("Reimu",   91002),
	"[Reimu] Cirno Defeated":                   TLocationData("Reimu",   91004),
	"[Reimu] Stage 2 Clear":                    TLocationData("Reimu",   91003),
	"[Reimu] Meiling - MidBoss":                TLocationData("Reimu",   91006),
	"[Reimu] Meiling Defeated":                 TLocationData("Reimu",   91007),
	"[Reimu] Stage 3 Clear":                    TLocationData("Reimu",   91005),
	"[Reimu] Koakuma Defeated":                 TLocationData("Reimu",   91008),
	"[Reimu] Patchouli Defeated":               TLocationData("Reimu",   91010),
	"[Reimu] Stage 4 Clear":                    TLocationData("Reimu",   91009),
	"[Reimu] Sakuya - MidBoss 1":               TLocationData("Reimu",   91012),
	"[Reimu] Sakuya Defeated":                  TLocationData("Reimu",   91013),
	"[Reimu] Stage 5 Clear":                    TLocationData("Reimu",   91011),
	"[Reimu] Sakuya - MidBoss 2":               TLocationData("Reimu",   91015),
	"[Reimu] Remilia Defeated":                 TLocationData("Reimu",   91016),
	"[Reimu] Stage 6 Clear":                    TLocationData("Reimu",   91014),
	"[Reimu] Patchouli - MidBoss":              TLocationData("Reimu",   91036),
	"[Reimu] Flandre Defeated":                 TLocationData("Reimu",   91037),
	"[Reimu] Stage Extra Clear":                TLocationData("Reimu",   91038),

	# Marisa
	"[Marisa] Rumia - MidBoss":                 TLocationData("Marisa",   91017),
	"[Marisa] Rumia Defeated":                  TLocationData("Marisa",   91018),
	"[Marisa] Stage 1 Clear":                   TLocationData("Marisa",   91035),
	"[Marisa] Daiyousei Defeated":              TLocationData("Marisa",   91019),
	"[Marisa] Cirno Defeated":                  TLocationData("Marisa",   91021),
	"[Marisa] Stage 2 Clear":                   TLocationData("Marisa",   91020),
	"[Marisa] Meiling - MidBoss":               TLocationData("Marisa",   91023),
	"[Marisa] Meiling Defeated":                TLocationData("Marisa",   91024),
	"[Marisa] Stage 3 Clear":                   TLocationData("Marisa",   91022),
	"[Marisa] Koakuma Defeated":                TLocationData("Marisa",   91025),
	"[Marisa] Patchouli Defeated":              TLocationData("Marisa",   91027),
	"[Marisa] Stage 4 Clear":                   TLocationData("Marisa",   91026),
	"[Marisa] Sakuya - MidBoss 1":              TLocationData("Marisa",   91029),
	"[Marisa] Sakuya Defeated":                 TLocationData("Marisa",   91030),
	"[Marisa] Stage 5 Clear":                   TLocationData("Marisa",   91028),
	"[Marisa] Sakuya - MidBoss 2":              TLocationData("Marisa",   91032),
	"[Marisa] Remilia Defeated":                TLocationData("Marisa",   91033),
	"[Marisa] Stage 6 Clear":                   TLocationData("Marisa",   91031),
	"[Marisa] Patchouli - MidBoss":             TLocationData("Marisa",   91039),
	"[Marisa] Flandre Defeated":                TLocationData("Marisa",   91040),
	"[Marisa] Stage Extra Clear":               TLocationData("Marisa",   91041),

	# Reimu - A
	"[Reimu A] Rumia - MidBoss":                  TLocationData("Reimu - A",   91042),
	"[Reimu A] Rumia Defeated":                   TLocationData("Reimu - A",   91043),
	"[Reimu A] Stage 1 Clear":                    TLocationData("Reimu - A",   91044),
	"[Reimu A] Daiyousei Defeated":               TLocationData("Reimu - A",   91045),
	"[Reimu A] Cirno Defeated":                   TLocationData("Reimu - A",   91046),
	"[Reimu A] Stage 2 Clear":                    TLocationData("Reimu - A",   91047),
	"[Reimu A] Meiling - MidBoss":                TLocationData("Reimu - A",   91048),
	"[Reimu A] Meiling Defeated":                 TLocationData("Reimu - A",   91049),
	"[Reimu A] Stage 3 Clear":                    TLocationData("Reimu - A",   91050),
	"[Reimu A] Koakuma Defeated":                 TLocationData("Reimu - A",   91051),
	"[Reimu A] Patchouli Defeated":               TLocationData("Reimu - A",   91052),
	"[Reimu A] Stage 4 Clear":                    TLocationData("Reimu - A",   91053),
	"[Reimu A] Sakuya - MidBoss 1":               TLocationData("Reimu - A",   91054),
	"[Reimu A] Sakuya Defeated":                  TLocationData("Reimu - A",   91055),
	"[Reimu A] Stage 5 Clear":                    TLocationData("Reimu - A",   91056),
	"[Reimu A] Sakuya - MidBoss 2":               TLocationData("Reimu - A",   91057),
	"[Reimu A] Remilia Defeated":                 TLocationData("Reimu - A",   91058),
	"[Reimu A] Stage 6 Clear":                    TLocationData("Reimu - A",   91059),
	"[Reimu A] Patchouli - MidBoss":              TLocationData("Reimu - A",   91060),
	"[Reimu A] Flandre Defeated":                 TLocationData("Reimu - A",   91061),
	"[Reimu A] Stage Extra Clear":                TLocationData("Reimu - A",   91062),

	# Reimu - B
	"[Reimu B] Rumia - MidBoss":                  TLocationData("Reimu - B",   91063),
	"[Reimu B] Rumia Defeated":                   TLocationData("Reimu - B",   91064),
	"[Reimu B] Stage 1 Clear":                    TLocationData("Reimu - B",   91065),
	"[Reimu B] Daiyousei Defeated":               TLocationData("Reimu - B",   91066),
	"[Reimu B] Cirno Defeated":                   TLocationData("Reimu - B",   91067),
	"[Reimu B] Stage 2 Clear":                    TLocationData("Reimu - B",   91068),
	"[Reimu B] Meiling - MidBoss":                TLocationData("Reimu - B",   91069),
	"[Reimu B] Meiling Defeated":                 TLocationData("Reimu - B",   91070),
	"[Reimu B] Stage 3 Clear":                    TLocationData("Reimu - B",   91071),
	"[Reimu B] Koakuma Defeated":                 TLocationData("Reimu - B",   91072),
	"[Reimu B] Patchouli Defeated":               TLocationData("Reimu - B",   91073),
	"[Reimu B] Stage 4 Clear":                    TLocationData("Reimu - B",   91074),
	"[Reimu B] Sakuya - MidBoss 1":               TLocationData("Reimu - B",   91075),
	"[Reimu B] Sakuya Defeated":                  TLocationData("Reimu - B",   91076),
	"[Reimu B] Stage 5 Clear":                    TLocationData("Reimu - B",   91077),
	"[Reimu B] Sakuya - MidBoss 2":               TLocationData("Reimu - B",   91078),
	"[Reimu B] Remilia Defeated":                 TLocationData("Reimu - B",   91079),
	"[Reimu B] Stage 6 Clear":                    TLocationData("Reimu - B",   91080),
	"[Reimu B] Patchouli - MidBoss":              TLocationData("Reimu - B",   91081),
	"[Reimu B] Flandre Defeated":                 TLocationData("Reimu - B",   91082),
	"[Reimu B] Stage Extra Clear":                TLocationData("Reimu - B",   91083),

	# Marisa - A
	"[Marisa A] Rumia - MidBoss":                  TLocationData("Marisa - A",   91084),
	"[Marisa A] Rumia Defeated":                   TLocationData("Marisa - A",   91085),
	"[Marisa A] Stage 1 Clear":                    TLocationData("Marisa - A",   91086),
	"[Marisa A] Daiyousei Defeated":               TLocationData("Marisa - A",   91087),
	"[Marisa A] Cirno Defeated":                   TLocationData("Marisa - A",   91088),
	"[Marisa A] Stage 2 Clear":                    TLocationData("Marisa - A",   91089),
	"[Marisa A] Meiling - MidBoss":                TLocationData("Marisa - A",   91090),
	"[Marisa A] Meiling Defeated":                 TLocationData("Marisa - A",   91091),
	"[Marisa A] Stage 3 Clear":                    TLocationData("Marisa - A",   91092),
	"[Marisa A] Koakuma Defeated":                 TLocationData("Marisa - A",   91093),
	"[Marisa A] Patchouli Defeated":               TLocationData("Marisa - A",   91094),
	"[Marisa A] Stage 4 Clear":                    TLocationData("Marisa - A",   91095),
	"[Marisa A] Sakuya - MidBoss 1":               TLocationData("Marisa - A",   91096),
	"[Marisa A] Sakuya Defeated":                  TLocationData("Marisa - A",   91097),
	"[Marisa A] Stage 5 Clear":                    TLocationData("Marisa - A",   91098),
	"[Marisa A] Sakuya - MidBoss 2":               TLocationData("Marisa - A",   91099),
	"[Marisa A] Remilia Defeated":                 TLocationData("Marisa - A",   91100),
	"[Marisa A] Stage 6 Clear":                    TLocationData("Marisa - A",   91101),
	"[Marisa A] Patchouli - MidBoss":              TLocationData("Marisa - A",   91102),
	"[Marisa A] Flandre Defeated":                 TLocationData("Marisa - A",   91103),
	"[Marisa A] Stage Extra Clear":                TLocationData("Marisa - A",   91104),

	# Marisa - B
	"[Marisa B] Rumia - MidBoss":                  TLocationData("Marisa - B",   91105),
	"[Marisa B] Rumia Defeated":                   TLocationData("Marisa - B",   91106),
	"[Marisa B] Stage 1 Clear":                    TLocationData("Marisa - B",   91107),
	"[Marisa B] Daiyousei Defeated":               TLocationData("Marisa - B",   91108),
	"[Marisa B] Cirno Defeated":                   TLocationData("Marisa - B",   91109),
	"[Marisa B] Stage 2 Clear":                    TLocationData("Marisa - B",   91110),
	"[Marisa B] Meiling - MidBoss":                TLocationData("Marisa - B",   91111),
	"[Marisa B] Meiling Defeated":                 TLocationData("Marisa - B",   91112),
	"[Marisa B] Stage 3 Clear":                    TLocationData("Marisa - B",   91113),
	"[Marisa B] Koakuma Defeated":                 TLocationData("Marisa - B",   91114),
	"[Marisa B] Patchouli Defeated":               TLocationData("Marisa - B",   91115),
	"[Marisa B] Stage 4 Clear":                    TLocationData("Marisa - B",   91116),
	"[Marisa B] Sakuya - MidBoss 1":               TLocationData("Marisa - B",   91117),
	"[Marisa B] Sakuya Defeated":                  TLocationData("Marisa - B",   91118),
	"[Marisa B] Stage 5 Clear":                    TLocationData("Marisa - B",   91119),
	"[Marisa B] Sakuya - MidBoss 2":               TLocationData("Marisa - B",   91120),
	"[Marisa B] Remilia Defeated":                 TLocationData("Marisa - B",   91121),
	"[Marisa B] Stage 6 Clear":                    TLocationData("Marisa - B",   91122),
	"[Marisa B] Patchouli - MidBoss":              TLocationData("Marisa - B",   91123),
	"[Marisa B] Flandre Defeated":                 TLocationData("Marisa - B",   91124),
	"[Marisa B] Stage Extra Clear":                TLocationData("Marisa - B",   91125),

	## Easy
	# Reimu
	"[Easy][Reimu] Rumia - MidBoss":                  TLocationData("Easy - Reimu",   91126),
	"[Easy][Reimu] Rumia Defeated":                   TLocationData("Easy - Reimu",   91127),
	# "[Easy][Reimu] Stage 1 Clear":                    TLocationData("Easy - Reimu",   91128),
	"[Easy][Reimu] Daiyousei Defeated":               TLocationData("Easy - Reimu",   91129),
	"[Easy][Reimu] Cirno Defeated":                   TLocationData("Easy - Reimu",   91130),
	# "[Easy][Reimu] Stage 2 Clear":                    TLocationData("Easy - Reimu",   91131),
	"[Easy][Reimu] Meiling - MidBoss":                TLocationData("Easy - Reimu",   91132),
	"[Easy][Reimu] Meiling Defeated":                 TLocationData("Easy - Reimu",   91133),
	# "[Easy][Reimu] Stage 3 Clear":                    TLocationData("Easy - Reimu",   91134),
	"[Easy][Reimu] Koakuma Defeated":                 TLocationData("Easy - Reimu",   91135),
	"[Easy][Reimu] Patchouli Defeated":               TLocationData("Easy - Reimu",   91136),
	# "[Easy][Reimu] Stage 4 Clear":                    TLocationData("Easy - Reimu",   91137),
	"[Easy][Reimu] Sakuya - MidBoss 1":               TLocationData("Easy - Reimu",   91138),
	"[Easy][Reimu] Sakuya Defeated":                  TLocationData("Easy - Reimu",   91139),
	# "[Easy][Reimu] Stage 5 Clear":                    TLocationData("Easy - Reimu",   91140),
	# "[Easy][Reimu] Sakuya - MidBoss 2":               TLocationData("Easy - Reimu",   91141),
	# "[Easy][Reimu] Remilia Defeated":                 TLocationData("Easy - Reimu",   91142),
	# "[Easy][Reimu] Stage 6 Clear":                    TLocationData("Easy - Reimu",   91143),

	# Marisa
	"[Easy][Marisa] Rumia - MidBoss":                 TLocationData("Easy - Marisa",   91144),
	"[Easy][Marisa] Rumia Defeated":                  TLocationData("Easy - Marisa",   91145),
	# "[Easy][Marisa] Stage 1 Clear":                   TLocationData("Easy - Marisa",   91146),
	"[Easy][Marisa] Daiyousei Defeated":              TLocationData("Easy - Marisa",   91147),
	"[Easy][Marisa] Cirno Defeated":                  TLocationData("Easy - Marisa",   91148),
	# "[Easy][Marisa] Stage 2 Clear":                   TLocationData("Easy - Marisa",   91149),
	"[Easy][Marisa] Meiling - MidBoss":               TLocationData("Easy - Marisa",   91150),
	"[Easy][Marisa] Meiling Defeated":                TLocationData("Easy - Marisa",   91151),
	# "[Easy][Marisa] Stage 3 Clear":                   TLocationData("Easy - Marisa",   91152),
	"[Easy][Marisa] Koakuma Defeated":                TLocationData("Easy - Marisa",   91153),
	"[Easy][Marisa] Patchouli Defeated":              TLocationData("Easy - Marisa",   91154),
	# "[Easy][Marisa] Stage 4 Clear":                   TLocationData("Easy - Marisa",   91155),
	"[Easy][Marisa] Sakuya - MidBoss 1":              TLocationData("Easy - Marisa",   91156),
	"[Easy][Marisa] Sakuya Defeated":                 TLocationData("Easy - Marisa",   91157),
	# "[Easy][Marisa] Stage 5 Clear":                   TLocationData("Easy - Marisa",   91158),
	# "[Easy][Marisa] Sakuya - MidBoss 2":              TLocationData("Easy - Marisa",   91159),
	# "[Easy][Marisa] Remilia Defeated":                TLocationData("Easy - Marisa",   91160),
	# "[Easy][Marisa] Stage 6 Clear":                   TLocationData("Easy - Marisa",   91161),

	# Reimu - A
	"[Easy][Reimu A] Rumia - MidBoss":                  TLocationData("Easy - Reimu - A",   91162),
	"[Easy][Reimu A] Rumia Defeated":                   TLocationData("Easy - Reimu - A",   91163),
	# "[Easy][Reimu A] Stage 1 Clear":                    TLocationData("Easy - Reimu - A",   91164),
	"[Easy][Reimu A] Daiyousei Defeated":               TLocationData("Easy - Reimu - A",   91165),
	"[Easy][Reimu A] Cirno Defeated":                   TLocationData("Easy - Reimu - A",   91166),
	# "[Easy][Reimu A] Stage 2 Clear":                    TLocationData("Easy - Reimu - A",   91167),
	"[Easy][Reimu A] Meiling - MidBoss":                TLocationData("Easy - Reimu - A",   91168),
	"[Easy][Reimu A] Meiling Defeated":                 TLocationData("Easy - Reimu - A",   91169),
	# "[Easy][Reimu A] Stage 3 Clear":                    TLocationData("Easy - Reimu - A",   91170),
	"[Easy][Reimu A] Koakuma Defeated":                 TLocationData("Easy - Reimu - A",   91171),
	"[Easy][Reimu A] Patchouli Defeated":               TLocationData("Easy - Reimu - A",   91172),
	# "[Easy][Reimu A] Stage 4 Clear":                    TLocationData("Easy - Reimu - A",   91173),
	"[Easy][Reimu A] Sakuya - MidBoss 1":               TLocationData("Easy - Reimu - A",   91174),
	"[Easy][Reimu A] Sakuya Defeated":                  TLocationData("Easy - Reimu - A",   91175),
	# "[Easy][Reimu A] Stage 5 Clear":                    TLocationData("Easy - Reimu - A",   91176),
	# "[Easy][Reimu A] Sakuya - MidBoss 2":               TLocationData("Easy - Reimu - A",   91177),
	# "[Easy][Reimu A] Remilia Defeated":                 TLocationData("Easy - Reimu - A",   91178),
	# "[Easy][Reimu A] Stage 6 Clear":                    TLocationData("Easy - Reimu - A",   91179),

	# Reimu - B
	"[Easy][Reimu B] Rumia - MidBoss":                  TLocationData("Easy - Reimu - B",   91180),
	"[Easy][Reimu B] Rumia Defeated":                   TLocationData("Easy - Reimu - B",   91181),
	# "[Easy][Reimu B] Stage 1 Clear":                    TLocationData("Easy - Reimu - B",   91182),
	"[Easy][Reimu B] Daiyousei Defeated":               TLocationData("Easy - Reimu - B",   91183),
	"[Easy][Reimu B] Cirno Defeated":                   TLocationData("Easy - Reimu - B",   91184),
	# "[Easy][Reimu B] Stage 2 Clear":                    TLocationData("Easy - Reimu - B",   91185),
	"[Easy][Reimu B] Meiling - MidBoss":                TLocationData("Easy - Reimu - B",   91186),
	"[Easy][Reimu B] Meiling Defeated":                 TLocationData("Easy - Reimu - B",   91187),
	# "[Easy][Reimu B] Stage 3 Clear":                    TLocationData("Easy - Reimu - B",   91188),
	"[Easy][Reimu B] Koakuma Defeated":                 TLocationData("Easy - Reimu - B",   91189),
	"[Easy][Reimu B] Patchouli Defeated":               TLocationData("Easy - Reimu - B",   91190),
	# "[Easy][Reimu B] Stage 4 Clear":                    TLocationData("Easy - Reimu - B",   91191),
	"[Easy][Reimu B] Sakuya - MidBoss 1":               TLocationData("Easy - Reimu - B",   91192),
	"[Easy][Reimu B] Sakuya Defeated":                  TLocationData("Easy - Reimu - B",   91193),
	# "[Easy][Reimu B] Stage 5 Clear":                    TLocationData("Easy - Reimu - B",   91194),
	# "[Easy][Reimu B] Sakuya - MidBoss 2":               TLocationData("Easy - Reimu - B",   91195),
	# "[Easy][Reimu B] Remilia Defeated":                 TLocationData("Easy - Reimu - B",   91196),
	# "[Easy][Reimu B] Stage 6 Clear":                    TLocationData("Easy - Reimu - B",   91197),

	# Marisa - A
	"[Easy][Marisa A] Rumia - MidBoss":                  TLocationData("Easy - Marisa - A",   91198),
	"[Easy][Marisa A] Rumia Defeated":                   TLocationData("Easy - Marisa - A",   91199),
	# "[Easy][Marisa A] Stage 1 Clear":                    TLocationData("Easy - Marisa - A",   91200),
	"[Easy][Marisa A] Daiyousei Defeated":               TLocationData("Easy - Marisa - A",   91201),
	"[Easy][Marisa A] Cirno Defeated":                   TLocationData("Easy - Marisa - A",   91202),
	# "[Easy][Marisa A] Stage 2 Clear":                    TLocationData("Easy - Marisa - A",   91203),
	"[Easy][Marisa A] Meiling - MidBoss":                TLocationData("Easy - Marisa - A",   91204),
	"[Easy][Marisa A] Meiling Defeated":                 TLocationData("Easy - Marisa - A",   91205),
	# "[Easy][Marisa A] Stage 3 Clear":                    TLocationData("Easy - Marisa - A",   91206),
	"[Easy][Marisa A] Koakuma Defeated":                 TLocationData("Easy - Marisa - A",   91207),
	"[Easy][Marisa A] Patchouli Defeated":               TLocationData("Easy - Marisa - A",   91208),
	# "[Easy][Marisa A] Stage 4 Clear":                    TLocationData("Easy - Marisa - A",   91209),
	"[Easy][Marisa A] Sakuya - MidBoss 1":               TLocationData("Easy - Marisa - A",   91210),
	"[Easy][Marisa A] Sakuya Defeated":                  TLocationData("Easy - Marisa - A",   91211),
	# "[Easy][Marisa A] Stage 5 Clear":                    TLocationData("Easy - Marisa - A",   91212),
	# "[Easy][Marisa A] Sakuya - MidBoss 2":               TLocationData("Easy - Marisa - A",   91213),
	# "[Easy][Marisa A] Remilia Defeated":                 TLocationData("Easy - Marisa - A",   91214),
	# "[Easy][Marisa A] Stage 6 Clear":                    TLocationData("Easy - Marisa - A",   91215),

	# Marisa - B
	"[Easy][Marisa B] Rumia - MidBoss":                  TLocationData("Easy - Marisa - B",   91216),
	"[Easy][Marisa B] Rumia Defeated":                   TLocationData("Easy - Marisa - B",   91217),
	# "[Easy][Marisa B] Stage 1 Clear":                    TLocationData("Easy - Marisa - B",   91218),
	"[Easy][Marisa B] Daiyousei Defeated":               TLocationData("Easy - Marisa - B",   91219),
	"[Easy][Marisa B] Cirno Defeated":                   TLocationData("Easy - Marisa - B",   91220),
	# "[Easy][Marisa B] Stage 2 Clear":                    TLocationData("Easy - Marisa - B",   91221),
	"[Easy][Marisa B] Meiling - MidBoss":                TLocationData("Easy - Marisa - B",   91222),
	"[Easy][Marisa B] Meiling Defeated":                 TLocationData("Easy - Marisa - B",   91223),
	# "[Easy][Marisa B] Stage 3 Clear":                    TLocationData("Easy - Marisa - B",   91224),
	"[Easy][Marisa B] Koakuma Defeated":                 TLocationData("Easy - Marisa - B",   91225),
	"[Easy][Marisa B] Patchouli Defeated":               TLocationData("Easy - Marisa - B",   91226),
	# "[Easy][Marisa B] Stage 4 Clear":                    TLocationData("Easy - Marisa - B",   91227),
	"[Easy][Marisa B] Sakuya - MidBoss 1":               TLocationData("Easy - Marisa - B",   91228),
	"[Easy][Marisa B] Sakuya Defeated":                  TLocationData("Easy - Marisa - B",   91229),
	# "[Easy][Marisa B] Stage 5 Clear":                    TLocationData("Easy - Marisa - B",   91230),
	# "[Easy][Marisa B] Sakuya - MidBoss 2":               TLocationData("Easy - Marisa - B",   91231),
	# "[Easy][Marisa B] Remilia Defeated":                 TLocationData("Easy - Marisa - B",   91232),
	# "[Easy][Marisa B] Stage 6 Clear":                    TLocationData("Easy - Marisa - B",   91233),

	## Normal
	# Reimu
	"[Normal][Reimu] Rumia - MidBoss":                  TLocationData("Normal - Reimu",   91234),
	"[Normal][Reimu] Rumia Defeated":                   TLocationData("Normal - Reimu",   91235),
	# "[Normal][Reimu] Stage 1 Clear":                    TLocationData("Normal - Reimu",   91236),
	"[Normal][Reimu] Daiyousei Defeated":               TLocationData("Normal - Reimu",   91237),
	"[Normal][Reimu] Cirno Defeated":                   TLocationData("Normal - Reimu",   91238),
	# "[Normal][Reimu] Stage 2 Clear":                    TLocationData("Normal - Reimu",   91239),
	"[Normal][Reimu] Meiling - MidBoss":                TLocationData("Normal - Reimu",   91240),
	"[Normal][Reimu] Meiling Defeated":                 TLocationData("Normal - Reimu",   91241),
	# "[Normal][Reimu] Stage 3 Clear":                    TLocationData("Normal - Reimu",   91242),
	"[Normal][Reimu] Koakuma Defeated":                 TLocationData("Normal - Reimu",   91243),
	"[Normal][Reimu] Patchouli Defeated":               TLocationData("Normal - Reimu",   91244),
	# "[Normal][Reimu] Stage 4 Clear":                    TLocationData("Normal - Reimu",   91245),
	"[Normal][Reimu] Sakuya - MidBoss 1":               TLocationData("Normal - Reimu",   91246),
	"[Normal][Reimu] Sakuya Defeated":                  TLocationData("Normal - Reimu",   91247),
	# "[Normal][Reimu] Stage 5 Clear":                    TLocationData("Normal - Reimu",   91248),
	"[Normal][Reimu] Sakuya - MidBoss 2":               TLocationData("Normal - Reimu",   91249),
	"[Normal][Reimu] Remilia Defeated":                 TLocationData("Normal - Reimu",   91250),
	# "[Normal][Reimu] Stage 6 Clear":                    TLocationData("Normal - Reimu",   91251),

	# Marisa
	"[Normal][Marisa] Rumia - MidBoss":                 TLocationData("Normal - Marisa",   91252),
	"[Normal][Marisa] Rumia Defeated":                  TLocationData("Normal - Marisa",   91253),
	# "[Normal][Marisa] Stage 1 Clear":                   TLocationData("Normal - Marisa",   91254),
	"[Normal][Marisa] Daiyousei Defeated":              TLocationData("Normal - Marisa",   91255),
	"[Normal][Marisa] Cirno Defeated":                  TLocationData("Normal - Marisa",   91256),
	# "[Normal][Marisa] Stage 2 Clear":                   TLocationData("Normal - Marisa",   91257),
	"[Normal][Marisa] Meiling - MidBoss":               TLocationData("Normal - Marisa",   91258),
	"[Normal][Marisa] Meiling Defeated":                TLocationData("Normal - Marisa",   91259),
	# "[Normal][Marisa] Stage 3 Clear":                   TLocationData("Normal - Marisa",   91260),
	"[Normal][Marisa] Koakuma Defeated":                TLocationData("Normal - Marisa",   91261),
	"[Normal][Marisa] Patchouli Defeated":              TLocationData("Normal - Marisa",   91262),
	# "[Normal][Marisa] Stage 4 Clear":                   TLocationData("Normal - Marisa",   91263),
	"[Normal][Marisa] Sakuya - MidBoss 1":              TLocationData("Normal - Marisa",   91264),
	"[Normal][Marisa] Sakuya Defeated":                 TLocationData("Normal - Marisa",   91265),
	# "[Normal][Marisa] Stage 5 Clear":                   TLocationData("Normal - Marisa",   91266),
	"[Normal][Marisa] Sakuya - MidBoss 2":              TLocationData("Normal - Marisa",   91267),
	"[Normal][Marisa] Remilia Defeated":                TLocationData("Normal - Marisa",   91268),
	# "[Normal][Marisa] Stage 6 Clear":                   TLocationData("Normal - Marisa",   91269),

	# Reimu - A
	"[Normal][Reimu A] Rumia - MidBoss":                  TLocationData("Normal - Reimu - A",   91270),
	"[Normal][Reimu A] Rumia Defeated":                   TLocationData("Normal - Reimu - A",   91271),
	# "[Normal][Reimu A] Stage 1 Clear":                    TLocationData("Normal - Reimu - A",   91272),
	"[Normal][Reimu A] Daiyousei Defeated":               TLocationData("Normal - Reimu - A",   91273),
	"[Normal][Reimu A] Cirno Defeated":                   TLocationData("Normal - Reimu - A",   91274),
	# "[Normal][Reimu A] Stage 2 Clear":                    TLocationData("Normal - Reimu - A",   91275),
	"[Normal][Reimu A] Meiling - MidBoss":                TLocationData("Normal - Reimu - A",   91276),
	"[Normal][Reimu A] Meiling Defeated":                 TLocationData("Normal - Reimu - A",   91277),
	# "[Normal][Reimu A] Stage 3 Clear":                    TLocationData("Normal - Reimu - A",   91278),
	"[Normal][Reimu A] Koakuma Defeated":                 TLocationData("Normal - Reimu - A",   91279),
	"[Normal][Reimu A] Patchouli Defeated":               TLocationData("Normal - Reimu - A",   91280),
	# "[Normal][Reimu A] Stage 4 Clear":                    TLocationData("Normal - Reimu - A",   91281),
	"[Normal][Reimu A] Sakuya - MidBoss 1":               TLocationData("Normal - Reimu - A",   91282),
	"[Normal][Reimu A] Sakuya Defeated":                  TLocationData("Normal - Reimu - A",   91283),
	# "[Normal][Reimu A] Stage 5 Clear":                    TLocationData("Normal - Reimu - A",   91284),
	"[Normal][Reimu A] Sakuya - MidBoss 2":               TLocationData("Normal - Reimu - A",   91285),
	"[Normal][Reimu A] Remilia Defeated":                 TLocationData("Normal - Reimu - A",   91286),
	# "[Normal][Reimu A] Stage 6 Clear":                    TLocationData("Normal - Reimu - A",   91287),

	# Reimu - B
	"[Normal][Reimu B] Rumia - MidBoss":                  TLocationData("Normal - Reimu - B",   91288),
	"[Normal][Reimu B] Rumia Defeated":                   TLocationData("Normal - Reimu - B",   91289),
	# "[Normal][Reimu B] Stage 1 Clear":                    TLocationData("Normal - Reimu - B",   91290),
	"[Normal][Reimu B] Daiyousei Defeated":               TLocationData("Normal - Reimu - B",   91291),
	"[Normal][Reimu B] Cirno Defeated":                   TLocationData("Normal - Reimu - B",   91292),
	# "[Normal][Reimu B] Stage 2 Clear":                    TLocationData("Normal - Reimu - B",   91293),
	"[Normal][Reimu B] Meiling - MidBoss":                TLocationData("Normal - Reimu - B",   91294),
	"[Normal][Reimu B] Meiling Defeated":                 TLocationData("Normal - Reimu - B",   91295),
	# "[Normal][Reimu B] Stage 3 Clear":                    TLocationData("Normal - Reimu - B",   91296),
	"[Normal][Reimu B] Koakuma Defeated":                 TLocationData("Normal - Reimu - B",   91297),
	"[Normal][Reimu B] Patchouli Defeated":               TLocationData("Normal - Reimu - B",   91298),
	# "[Normal][Reimu B] Stage 4 Clear":                    TLocationData("Normal - Reimu - B",   91299),
	"[Normal][Reimu B] Sakuya - MidBoss 1":               TLocationData("Normal - Reimu - B",   91300),
	"[Normal][Reimu B] Sakuya Defeated":                  TLocationData("Normal - Reimu - B",   91301),
	# "[Normal][Reimu B] Stage 5 Clear":                    TLocationData("Normal - Reimu - B",   91302),
	"[Normal][Reimu B] Sakuya - MidBoss 2":               TLocationData("Normal - Reimu - B",   91303),
	"[Normal][Reimu B] Remilia Defeated":                 TLocationData("Normal - Reimu - B",   91304),
	# "[Normal][Reimu B] Stage 6 Clear":                    TLocationData("Normal - Reimu - B",   91305),

	# Marisa - A
	"[Normal][Marisa A] Rumia - MidBoss":                  TLocationData("Normal - Marisa - A",   91306),
	"[Normal][Marisa A] Rumia Defeated":                   TLocationData("Normal - Marisa - A",   91307),
	# "[Normal][Marisa A] Stage 1 Clear":                    TLocationData("Normal - Marisa - A",   91308),
	"[Normal][Marisa A] Daiyousei Defeated":               TLocationData("Normal - Marisa - A",   91309),
	"[Normal][Marisa A] Cirno Defeated":                   TLocationData("Normal - Marisa - A",   91310),
	# "[Normal][Marisa A] Stage 2 Clear":                    TLocationData("Normal - Marisa - A",   91311),
	"[Normal][Marisa A] Meiling - MidBoss":                TLocationData("Normal - Marisa - A",   91312),
	"[Normal][Marisa A] Meiling Defeated":                 TLocationData("Normal - Marisa - A",   91313),
	# "[Normal][Marisa A] Stage 3 Clear":                    TLocationData("Normal - Marisa - A",   91314),
	"[Normal][Marisa A] Koakuma Defeated":                 TLocationData("Normal - Marisa - A",   91315),
	"[Normal][Marisa A] Patchouli Defeated":               TLocationData("Normal - Marisa - A",   91316),
	# "[Normal][Marisa A] Stage 4 Clear":                    TLocationData("Normal - Marisa - A",   91317),
	"[Normal][Marisa A] Sakuya - MidBoss 1":               TLocationData("Normal - Marisa - A",   91318),
	"[Normal][Marisa A] Sakuya Defeated":                  TLocationData("Normal - Marisa - A",   91319),
	# "[Normal][Marisa A] Stage 5 Clear":                    TLocationData("Normal - Marisa - A",   91320),
	"[Normal][Marisa A] Sakuya - MidBoss 2":               TLocationData("Normal - Marisa - A",   91321),
	"[Normal][Marisa A] Remilia Defeated":                 TLocationData("Normal - Marisa - A",   91322),
	# "[Normal][Marisa A] Stage 6 Clear":                    TLocationData("Normal - Marisa - A",   91323),

	# Marisa - B
	"[Normal][Marisa B] Rumia - MidBoss":                  TLocationData("Normal - Marisa - B",   91324),
	"[Normal][Marisa B] Rumia Defeated":                   TLocationData("Normal - Marisa - B",   91325),
	# "[Normal][Marisa B] Stage 1 Clear":                    TLocationData("Normal - Marisa - B",   91326),
	"[Normal][Marisa B] Daiyousei Defeated":               TLocationData("Normal - Marisa - B",   91327),
	"[Normal][Marisa B] Cirno Defeated":                   TLocationData("Normal - Marisa - B",   91328),
	# "[Normal][Marisa B] Stage 2 Clear":                    TLocationData("Normal - Marisa - B",   91329),
	"[Normal][Marisa B] Meiling - MidBoss":                TLocationData("Normal - Marisa - B",   91330),
	"[Normal][Marisa B] Meiling Defeated":                 TLocationData("Normal - Marisa - B",   91331),
	# "[Normal][Marisa B] Stage 3 Clear":                    TLocationData("Normal - Marisa - B",   91332),
	"[Normal][Marisa B] Koakuma Defeated":                 TLocationData("Normal - Marisa - B",   91333),
	"[Normal][Marisa B] Patchouli Defeated":               TLocationData("Normal - Marisa - B",   91334),
	# "[Normal][Marisa B] Stage 4 Clear":                    TLocationData("Normal - Marisa - B",   91335),
	"[Normal][Marisa B] Sakuya - MidBoss 1":               TLocationData("Normal - Marisa - B",   91336),
	"[Normal][Marisa B] Sakuya Defeated":                  TLocationData("Normal - Marisa - B",   91337),
	# "[Normal][Marisa B] Stage 5 Clear":                    TLocationData("Normal - Marisa - B",   91338),
	"[Normal][Marisa B] Sakuya - MidBoss 2":               TLocationData("Normal - Marisa - B",   91339),
	"[Normal][Marisa B] Remilia Defeated":                 TLocationData("Normal - Marisa - B",   91340),
	# "[Normal][Marisa B] Stage 6 Clear":                    TLocationData("Normal - Marisa - B",   91341),

	## Hard
	# Reimu
	"[Hard][Reimu] Rumia - MidBoss":                  TLocationData("Hard - Reimu",   91342),
	"[Hard][Reimu] Rumia Defeated":                   TLocationData("Hard - Reimu",   91343),
	# "[Hard][Reimu] Stage 1 Clear":                    TLocationData("Hard - Reimu",   91344),
	"[Hard][Reimu] Daiyousei Defeated":               TLocationData("Hard - Reimu",   91345),
	"[Hard][Reimu] Cirno Defeated":                   TLocationData("Hard - Reimu",   91346),
	# "[Hard][Reimu] Stage 2 Clear":                    TLocationData("Hard - Reimu",   91347),
	"[Hard][Reimu] Meiling - MidBoss":                TLocationData("Hard - Reimu",   91348),
	"[Hard][Reimu] Meiling Defeated":                 TLocationData("Hard - Reimu",   91349),
	# "[Hard][Reimu] Stage 3 Clear":                    TLocationData("Hard - Reimu",   91350),
	"[Hard][Reimu] Koakuma Defeated":                 TLocationData("Hard - Reimu",   91351),
	"[Hard][Reimu] Patchouli Defeated":               TLocationData("Hard - Reimu",   91352),
	# "[Hard][Reimu] Stage 4 Clear":                    TLocationData("Hard - Reimu",   91353),
	"[Hard][Reimu] Sakuya - MidBoss 1":               TLocationData("Hard - Reimu",   91354),
	"[Hard][Reimu] Sakuya Defeated":                  TLocationData("Hard - Reimu",   91355),
	# "[Hard][Reimu] Stage 5 Clear":                    TLocationData("Hard - Reimu",   91356),
	"[Hard][Reimu] Sakuya - MidBoss 2":               TLocationData("Hard - Reimu",   91357),
	"[Hard][Reimu] Remilia Defeated":                 TLocationData("Hard - Reimu",   91358),
	# "[Hard][Reimu] Stage 6 Clear":                    TLocationData("Hard - Reimu",   91359),

	# Marisa
	"[Hard][Marisa] Rumia - MidBoss":                 TLocationData("Hard - Marisa",   91360),
	"[Hard][Marisa] Rumia Defeated":                  TLocationData("Hard - Marisa",   91361),
	# "[Hard][Marisa] Stage 1 Clear":                   TLocationData("Hard - Marisa",   91362),
	"[Hard][Marisa] Daiyousei Defeated":              TLocationData("Hard - Marisa",   91363),
	"[Hard][Marisa] Cirno Defeated":                  TLocationData("Hard - Marisa",   91364),
	# "[Hard][Marisa] Stage 2 Clear":                   TLocationData("Hard - Marisa",   91365),
	"[Hard][Marisa] Meiling - MidBoss":               TLocationData("Hard - Marisa",   91366),
	"[Hard][Marisa] Meiling Defeated":                TLocationData("Hard - Marisa",   91367),
	# "[Hard][Marisa] Stage 3 Clear":                   TLocationData("Hard - Marisa",   91368),
	"[Hard][Marisa] Koakuma Defeated":                TLocationData("Hard - Marisa",   91369),
	"[Hard][Marisa] Patchouli Defeated":              TLocationData("Hard - Marisa",   91370),
	# "[Hard][Marisa] Stage 4 Clear":                   TLocationData("Hard - Marisa",   91371),
	"[Hard][Marisa] Sakuya - MidBoss 1":              TLocationData("Hard - Marisa",   91372),
	"[Hard][Marisa] Sakuya Defeated":                 TLocationData("Hard - Marisa",   91373),
	# "[Hard][Marisa] Stage 5 Clear":                   TLocationData("Hard - Marisa",   91374),
	"[Hard][Marisa] Sakuya - MidBoss 2":              TLocationData("Hard - Marisa",   91375),
	"[Hard][Marisa] Remilia Defeated":                TLocationData("Hard - Marisa",   91376),
	# "[Hard][Marisa] Stage 6 Clear":                   TLocationData("Hard - Marisa",   91377),

	# Reimu - A
	"[Hard][Reimu A] Rumia - MidBoss":                  TLocationData("Hard - Reimu - A",   91378),
	"[Hard][Reimu A] Rumia Defeated":                   TLocationData("Hard - Reimu - A",   91379),
	# "[Hard][Reimu A] Stage 1 Clear":                    TLocationData("Hard - Reimu - A",   91380),
	"[Hard][Reimu A] Daiyousei Defeated":               TLocationData("Hard - Reimu - A",   91381),
	"[Hard][Reimu A] Cirno Defeated":                   TLocationData("Hard - Reimu - A",   91382),
	# "[Hard][Reimu A] Stage 2 Clear":                    TLocationData("Hard - Reimu - A",   91383),
	"[Hard][Reimu A] Meiling - MidBoss":                TLocationData("Hard - Reimu - A",   91384),
	"[Hard][Reimu A] Meiling Defeated":                 TLocationData("Hard - Reimu - A",   91385),
	# "[Hard][Reimu A] Stage 3 Clear":                    TLocationData("Hard - Reimu - A",   91386),
	"[Hard][Reimu A] Koakuma Defeated":                 TLocationData("Hard - Reimu - A",   91387),
	"[Hard][Reimu A] Patchouli Defeated":               TLocationData("Hard - Reimu - A",   91388),
	# "[Hard][Reimu A] Stage 4 Clear":                    TLocationData("Hard - Reimu - A",   91389),
	"[Hard][Reimu A] Sakuya - MidBoss 1":               TLocationData("Hard - Reimu - A",   91390),
	"[Hard][Reimu A] Sakuya Defeated":                  TLocationData("Hard - Reimu - A",   91391),
	# "[Hard][Reimu A] Stage 5 Clear":                    TLocationData("Hard - Reimu - A",   91392),
	"[Hard][Reimu A] Sakuya - MidBoss 2":               TLocationData("Hard - Reimu - A",   91393),
	"[Hard][Reimu A] Remilia Defeated":                 TLocationData("Hard - Reimu - A",   91394),
	# "[Hard][Reimu A] Stage 6 Clear":                    TLocationData("Hard - Reimu - A",   91395),

	# Reimu - B
	"[Hard][Reimu B] Rumia - MidBoss":                  TLocationData("Hard - Reimu - B",   91396),
	"[Hard][Reimu B] Rumia Defeated":                   TLocationData("Hard - Reimu - B",   91397),
	# "[Hard][Reimu B] Stage 1 Clear":                    TLocationData("Hard - Reimu - B",   91398),
	"[Hard][Reimu B] Daiyousei Defeated":               TLocationData("Hard - Reimu - B",   91399),
	"[Hard][Reimu B] Cirno Defeated":                   TLocationData("Hard - Reimu - B",   91400),
	# "[Hard][Reimu B] Stage 2 Clear":                    TLocationData("Hard - Reimu - B",   91401),
	"[Hard][Reimu B] Meiling - MidBoss":                TLocationData("Hard - Reimu - B",   91402),
	"[Hard][Reimu B] Meiling Defeated":                 TLocationData("Hard - Reimu - B",   91403),
	# "[Hard][Reimu B] Stage 3 Clear":                    TLocationData("Hard - Reimu - B",   91404),
	"[Hard][Reimu B] Koakuma Defeated":                 TLocationData("Hard - Reimu - B",   91405),
	"[Hard][Reimu B] Patchouli Defeated":               TLocationData("Hard - Reimu - B",   91406),
	# "[Hard][Reimu B] Stage 4 Clear":                    TLocationData("Hard - Reimu - B",   91407),
	"[Hard][Reimu B] Sakuya - MidBoss 1":               TLocationData("Hard - Reimu - B",   91408),
	"[Hard][Reimu B] Sakuya Defeated":                  TLocationData("Hard - Reimu - B",   91409),
	# "[Hard][Reimu B] Stage 5 Clear":                    TLocationData("Hard - Reimu - B",   91410),
	"[Hard][Reimu B] Sakuya - MidBoss 2":               TLocationData("Hard - Reimu - B",   91411),
	"[Hard][Reimu B] Remilia Defeated":                 TLocationData("Hard - Reimu - B",   91412),
	# "[Hard][Reimu B] Stage 6 Clear":                    TLocationData("Hard - Reimu - B",   91413),

	# Marisa - A
	"[Hard][Marisa A] Rumia - MidBoss":                  TLocationData("Hard - Marisa - A",   91414),
	"[Hard][Marisa A] Rumia Defeated":                   TLocationData("Hard - Marisa - A",   91415),
	# "[Hard][Marisa A] Stage 1 Clear":                    TLocationData("Hard - Marisa - A",   91416),
	"[Hard][Marisa A] Daiyousei Defeated":               TLocationData("Hard - Marisa - A",   91417),
	"[Hard][Marisa A] Cirno Defeated":                   TLocationData("Hard - Marisa - A",   91418),
	# "[Hard][Marisa A] Stage 2 Clear":                    TLocationData("Hard - Marisa - A",   91419),
	"[Hard][Marisa A] Meiling - MidBoss":                TLocationData("Hard - Marisa - A",   91420),
	"[Hard][Marisa A] Meiling Defeated":                 TLocationData("Hard - Marisa - A",   91421),
	# "[Hard][Marisa A] Stage 3 Clear":                    TLocationData("Hard - Marisa - A",   91422),
	"[Hard][Marisa A] Koakuma Defeated":                 TLocationData("Hard - Marisa - A",   91423),
	"[Hard][Marisa A] Patchouli Defeated":               TLocationData("Hard - Marisa - A",   91424),
	# "[Hard][Marisa A] Stage 4 Clear":                    TLocationData("Hard - Marisa - A",   91425),
	"[Hard][Marisa A] Sakuya - MidBoss 1":               TLocationData("Hard - Marisa - A",   91426),
	"[Hard][Marisa A] Sakuya Defeated":                  TLocationData("Hard - Marisa - A",   91427),
	# "[Hard][Marisa A] Stage 5 Clear":                    TLocationData("Hard - Marisa - A",   91428),
	"[Hard][Marisa A] Sakuya - MidBoss 2":               TLocationData("Hard - Marisa - A",   91429),
	"[Hard][Marisa A] Remilia Defeated":                 TLocationData("Hard - Marisa - A",   91430),
	# "[Hard][Marisa A] Stage 6 Clear":                    TLocationData("Hard - Marisa - A",   91431),

	# Marisa - B
	"[Hard][Marisa B] Rumia - MidBoss":                  TLocationData("Hard - Marisa - B",   91432),
	"[Hard][Marisa B] Rumia Defeated":                   TLocationData("Hard - Marisa - B",   91433),
	# "[Hard][Marisa B] Stage 1 Clear":                    TLocationData("Hard - Marisa - B",   91434),
	"[Hard][Marisa B] Daiyousei Defeated":               TLocationData("Hard - Marisa - B",   91435),
	"[Hard][Marisa B] Cirno Defeated":                   TLocationData("Hard - Marisa - B",   91436),
	# "[Hard][Marisa B] Stage 2 Clear":                    TLocationData("Hard - Marisa - B",   91437),
	"[Hard][Marisa B] Meiling - MidBoss":                TLocationData("Hard - Marisa - B",   91438),
	"[Hard][Marisa B] Meiling Defeated":                 TLocationData("Hard - Marisa - B",   91439),
	# "[Hard][Marisa B] Stage 3 Clear":                    TLocationData("Hard - Marisa - B",   91440),
	"[Hard][Marisa B] Koakuma Defeated":                 TLocationData("Hard - Marisa - B",   91441),
	"[Hard][Marisa B] Patchouli Defeated":               TLocationData("Hard - Marisa - B",   91442),
	# "[Hard][Marisa B] Stage 4 Clear":                    TLocationData("Hard - Marisa - B",   91443),
	"[Hard][Marisa B] Sakuya - MidBoss 1":               TLocationData("Hard - Marisa - B",   91444),
	"[Hard][Marisa B] Sakuya Defeated":                  TLocationData("Hard - Marisa - B",   91445),
	# "[Hard][Marisa B] Stage 5 Clear":                    TLocationData("Hard - Marisa - B",   91446),
	"[Hard][Marisa B] Sakuya - MidBoss 2":               TLocationData("Hard - Marisa - B",   91447),
	"[Hard][Marisa B] Remilia Defeated":                 TLocationData("Hard - Marisa - B",   91448),
	# "[Hard][Marisa B] Stage 6 Clear":                    TLocationData("Hard - Marisa - B",   91449),

	## Lunatic
	# Reimu
	"[Lunatic][Reimu] Rumia - MidBoss":                  TLocationData("Lunatic - Reimu",   91450),
	"[Lunatic][Reimu] Rumia Defeated":                   TLocationData("Lunatic - Reimu",   91451),
	# "[Lunatic][Reimu] Stage 1 Clear":                    TLocationData("Lunatic - Reimu",   91452),
	"[Lunatic][Reimu] Daiyousei Defeated":               TLocationData("Lunatic - Reimu",   91453),
	"[Lunatic][Reimu] Cirno Defeated":                   TLocationData("Lunatic - Reimu",   91454),
	# "[Lunatic][Reimu] Stage 2 Clear":                    TLocationData("Lunatic - Reimu",   91455),
	"[Lunatic][Reimu] Meiling - MidBoss":                TLocationData("Lunatic - Reimu",   91456),
	"[Lunatic][Reimu] Meiling Defeated":                 TLocationData("Lunatic - Reimu",   91457),
	# "[Lunatic][Reimu] Stage 3 Clear":                    TLocationData("Lunatic - Reimu",   91458),
	"[Lunatic][Reimu] Koakuma Defeated":                 TLocationData("Lunatic - Reimu",   91459),
	"[Lunatic][Reimu] Patchouli Defeated":               TLocationData("Lunatic - Reimu",   91460),
	# "[Lunatic][Reimu] Stage 4 Clear":                    TLocationData("Lunatic - Reimu",   91461),
	"[Lunatic][Reimu] Sakuya - MidBoss 1":               TLocationData("Lunatic - Reimu",   91462),
	"[Lunatic][Reimu] Sakuya Defeated":                  TLocationData("Lunatic - Reimu",   91463),
	# "[Lunatic][Reimu] Stage 5 Clear":                    TLocationData("Lunatic - Reimu",   91464),
	"[Lunatic][Reimu] Sakuya - MidBoss 2":               TLocationData("Lunatic - Reimu",   91465),
	"[Lunatic][Reimu] Remilia Defeated":                 TLocationData("Lunatic - Reimu",   91466),
	# "[Lunatic][Reimu] Stage 6 Clear":                    TLocationData("Lunatic - Reimu",   91467),

	# Marisa
	"[Lunatic][Marisa] Rumia - MidBoss":                 TLocationData("Lunatic - Marisa",   91468),
	"[Lunatic][Marisa] Rumia Defeated":                  TLocationData("Lunatic - Marisa",   91469),
	# "[Lunatic][Marisa] Stage 1 Clear":                   TLocationData("Lunatic - Marisa",   91470),
	"[Lunatic][Marisa] Daiyousei Defeated":              TLocationData("Lunatic - Marisa",   91471),
	"[Lunatic][Marisa] Cirno Defeated":                  TLocationData("Lunatic - Marisa",   91472),
	# "[Lunatic][Marisa] Stage 2 Clear":                   TLocationData("Lunatic - Marisa",   91473),
	"[Lunatic][Marisa] Meiling - MidBoss":               TLocationData("Lunatic - Marisa",   91474),
	"[Lunatic][Marisa] Meiling Defeated":                TLocationData("Lunatic - Marisa",   91475),
	# "[Lunatic][Marisa] Stage 3 Clear":                   TLocationData("Lunatic - Marisa",   91476),
	"[Lunatic][Marisa] Koakuma Defeated":                TLocationData("Lunatic - Marisa",   91477),
	"[Lunatic][Marisa] Patchouli Defeated":              TLocationData("Lunatic - Marisa",   91478),
	# "[Lunatic][Marisa] Stage 4 Clear":                   TLocationData("Lunatic - Marisa",   91479),
	"[Lunatic][Marisa] Sakuya - MidBoss 1":              TLocationData("Lunatic - Marisa",   91480),
	"[Lunatic][Marisa] Sakuya Defeated":                 TLocationData("Lunatic - Marisa",   91481),
	# "[Lunatic][Marisa] Stage 5 Clear":                   TLocationData("Lunatic - Marisa",   91482),
	"[Lunatic][Marisa] Sakuya - MidBoss 2":              TLocationData("Lunatic - Marisa",   91483),
	"[Lunatic][Marisa] Remilia Defeated":                TLocationData("Lunatic - Marisa",   91484),
	# "[Lunatic][Marisa] Stage 6 Clear":                   TLocationData("Lunatic - Marisa",   91485),

	# Reimu - A
	"[Lunatic][Reimu A] Rumia - MidBoss":                  TLocationData("Lunatic - Reimu - A",   91486),
	"[Lunatic][Reimu A] Rumia Defeated":                   TLocationData("Lunatic - Reimu - A",   91487),
	# "[Lunatic][Reimu A] Stage 1 Clear":                    TLocationData("Lunatic - Reimu - A",   91488),
	"[Lunatic][Reimu A] Daiyousei Defeated":               TLocationData("Lunatic - Reimu - A",   91489),
	"[Lunatic][Reimu A] Cirno Defeated":                   TLocationData("Lunatic - Reimu - A",   91490),
	# "[Lunatic][Reimu A] Stage 2 Clear":                    TLocationData("Lunatic - Reimu - A",   91491),
	"[Lunatic][Reimu A] Meiling - MidBoss":                TLocationData("Lunatic - Reimu - A",   91492),
	"[Lunatic][Reimu A] Meiling Defeated":                 TLocationData("Lunatic - Reimu - A",   91493),
	# "[Lunatic][Reimu A] Stage 3 Clear":                    TLocationData("Lunatic - Reimu - A",   91494),
	"[Lunatic][Reimu A] Koakuma Defeated":                 TLocationData("Lunatic - Reimu - A",   91495),
	"[Lunatic][Reimu A] Patchouli Defeated":               TLocationData("Lunatic - Reimu - A",   91496),
	# "[Lunatic][Reimu A] Stage 4 Clear":                    TLocationData("Lunatic - Reimu - A",   91497),
	"[Lunatic][Reimu A] Sakuya - MidBoss 1":               TLocationData("Lunatic - Reimu - A",   91498),
	"[Lunatic][Reimu A] Sakuya Defeated":                  TLocationData("Lunatic - Reimu - A",   91499),
	# "[Lunatic][Reimu A] Stage 5 Clear":                    TLocationData("Lunatic - Reimu - A",   91500),
	"[Lunatic][Reimu A] Sakuya - MidBoss 2":               TLocationData("Lunatic - Reimu - A",   91501),
	"[Lunatic][Reimu A] Remilia Defeated":                 TLocationData("Lunatic - Reimu - A",   91502),
	# "[Lunatic][Reimu A] Stage 6 Clear":                    TLocationData("Lunatic - Reimu - A",   91503),

	# Reimu - B
	"[Lunatic][Reimu B] Rumia - MidBoss":                  TLocationData("Lunatic - Reimu - B",   91504),
	"[Lunatic][Reimu B] Rumia Defeated":                   TLocationData("Lunatic - Reimu - B",   91505),
	# "[Lunatic][Reimu B] Stage 1 Clear":                    TLocationData("Lunatic - Reimu - B",   91506),
	"[Lunatic][Reimu B] Daiyousei Defeated":               TLocationData("Lunatic - Reimu - B",   91507),
	"[Lunatic][Reimu B] Cirno Defeated":                   TLocationData("Lunatic - Reimu - B",   91508),
	# "[Lunatic][Reimu B] Stage 2 Clear":                    TLocationData("Lunatic - Reimu - B",   91509),
	"[Lunatic][Reimu B] Meiling - MidBoss":                TLocationData("Lunatic - Reimu - B",   91510),
	"[Lunatic][Reimu B] Meiling Defeated":                 TLocationData("Lunatic - Reimu - B",   91511),
	# "[Lunatic][Reimu B] Stage 3 Clear":                    TLocationData("Lunatic - Reimu - B",   91512),
	"[Lunatic][Reimu B] Koakuma Defeated":                 TLocationData("Lunatic - Reimu - B",   91513),
	"[Lunatic][Reimu B] Patchouli Defeated":               TLocationData("Lunatic - Reimu - B",   91514),
	# "[Lunatic][Reimu B] Stage 4 Clear":                    TLocationData("Lunatic - Reimu - B",   91515),
	"[Lunatic][Reimu B] Sakuya - MidBoss 1":               TLocationData("Lunatic - Reimu - B",   91516),
	"[Lunatic][Reimu B] Sakuya Defeated":                  TLocationData("Lunatic - Reimu - B",   91517),
	# "[Lunatic][Reimu B] Stage 5 Clear":                    TLocationData("Lunatic - Reimu - B",   91518),
	"[Lunatic][Reimu B] Sakuya - MidBoss 2":               TLocationData("Lunatic - Reimu - B",   91519),
	"[Lunatic][Reimu B] Remilia Defeated":                 TLocationData("Lunatic - Reimu - B",   91520),
	# "[Lunatic][Reimu B] Stage 6 Clear":                    TLocationData("Lunatic - Reimu - B",   91521),

	# Marisa - A
	"[Lunatic][Marisa A] Rumia - MidBoss":                  TLocationData("Lunatic - Marisa - A",   91522),
	"[Lunatic][Marisa A] Rumia Defeated":                   TLocationData("Lunatic - Marisa - A",   91523),
	# "[Lunatic][Marisa A] Stage 1 Clear":                    TLocationData("Lunatic - Marisa - A",   91524),
	"[Lunatic][Marisa A] Daiyousei Defeated":               TLocationData("Lunatic - Marisa - A",   91525),
	"[Lunatic][Marisa A] Cirno Defeated":                   TLocationData("Lunatic - Marisa - A",   91526),
	# "[Lunatic][Marisa A] Stage 2 Clear":                    TLocationData("Lunatic - Marisa - A",   91527),
	"[Lunatic][Marisa A] Meiling - MidBoss":                TLocationData("Lunatic - Marisa - A",   91528),
	"[Lunatic][Marisa A] Meiling Defeated":                 TLocationData("Lunatic - Marisa - A",   91529),
	# "[Lunatic][Marisa A] Stage 3 Clear":                    TLocationData("Lunatic - Marisa - A",   91530),
	"[Lunatic][Marisa A] Koakuma Defeated":                 TLocationData("Lunatic - Marisa - A",   91531),
	"[Lunatic][Marisa A] Patchouli Defeated":               TLocationData("Lunatic - Marisa - A",   91532),
	# "[Lunatic][Marisa A] Stage 4 Clear":                    TLocationData("Lunatic - Marisa - A",   91533),
	"[Lunatic][Marisa A] Sakuya - MidBoss 1":               TLocationData("Lunatic - Marisa - A",   91534),
	"[Lunatic][Marisa A] Sakuya Defeated":                  TLocationData("Lunatic - Marisa - A",   91535),
	# "[Lunatic][Marisa A] Stage 5 Clear":                    TLocationData("Lunatic - Marisa - A",   91536),
	"[Lunatic][Marisa A] Sakuya - MidBoss 2":               TLocationData("Lunatic - Marisa - A",   91537),
	"[Lunatic][Marisa A] Remilia Defeated":                 TLocationData("Lunatic - Marisa - A",   91538),
	# "[Lunatic][Marisa A] Stage 6 Clear":                    TLocationData("Lunatic - Marisa - A",   91539),

	# Marisa - B
	"[Lunatic][Marisa B] Rumia - MidBoss":                  TLocationData("Lunatic - Marisa - B",   91540),
	"[Lunatic][Marisa B] Rumia Defeated":                   TLocationData("Lunatic - Marisa - B",   91541),
	# "[Lunatic][Marisa B] Stage 1 Clear":                    TLocationData("Lunatic - Marisa - B",   91542),
	"[Lunatic][Marisa B] Daiyousei Defeated":               TLocationData("Lunatic - Marisa - B",   91543),
	"[Lunatic][Marisa B] Cirno Defeated":                   TLocationData("Lunatic - Marisa - B",   91544),
	# "[Lunatic][Marisa B] Stage 2 Clear":                    TLocationData("Lunatic - Marisa - B",   91545),
	"[Lunatic][Marisa B] Meiling - MidBoss":                TLocationData("Lunatic - Marisa - B",   91546),
	"[Lunatic][Marisa B] Meiling Defeated":                 TLocationData("Lunatic - Marisa - B",   91547),
	# "[Lunatic][Marisa B] Stage 3 Clear":                    TLocationData("Lunatic - Marisa - B",   91548),
	"[Lunatic][Marisa B] Koakuma Defeated":                 TLocationData("Lunatic - Marisa - B",   91549),
	"[Lunatic][Marisa B] Patchouli Defeated":               TLocationData("Lunatic - Marisa - B",   91550),
	# "[Lunatic][Marisa B] Stage 4 Clear":                    TLocationData("Lunatic - Marisa - B",   91551),
	"[Lunatic][Marisa B] Sakuya - MidBoss 1":               TLocationData("Lunatic - Marisa - B",   91552),
	"[Lunatic][Marisa B] Sakuya Defeated":                  TLocationData("Lunatic - Marisa - B",   91553),
	# "[Lunatic][Marisa B] Stage 5 Clear":                    TLocationData("Lunatic - Marisa - B",   91554),
	"[Lunatic][Marisa B] Sakuya - MidBoss 2":               TLocationData("Lunatic - Marisa - B",   91555),
	"[Lunatic][Marisa B] Remilia Defeated":                 TLocationData("Lunatic - Marisa - B",   91556),
	# "[Lunatic][Marisa B] Stage 6 Clear":                    TLocationData("Lunatic - Marisa - B",   91557),
}